# MIT License

# Copyright (c) 2025 Giuseppe Sorrentino, Paolo Salvatore Galfano, Davide Conficconi, Eleonora D'Arnese

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


import math
import sys
import numpy as np

def generate_range_defines(BI, step = 32, byte = True, suffix=""):
    lines = []
    for i in range(0, BI):
        lines.append(f"#define RANGE_{suffix}{format(step*(i+1), '03d')}_{format(step*i, '03d')} {(8 if byte else 1)*step*(i+1)-1}, {(8 if byte else 1)*step*i}")
    return lines

# used to generate the setup_interpolator_body.hpp file
def generate_write(PE, BI):
    lines = []
    lines.append("#pragma once")
    lines.append("\n// This file is generated by data_movers/movers_generator.py\n")

    lines.extend(generate_range_defines(BI))

    # ----------------- SETUP_INTERPOLATOR_SIGNATURE -----------------

    lines.append("")
    lines.append("#define SETUP_INTERPOLATOR_SIGNATURE \\")
    for i in range(0, PE):
        comma = "," if i < PE - 1 else ""
        lines.append(f"\thls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_{i+1}{comma} \\")
    lines.append("")

    # ----------------- SETUP_INTERPOLATOR_TESTBENCH_CALL -----------------
    lines.append("#define SETUP_INTERPOLATOR_TESTBENCH_CALL(x) \\")
    for i in range(0, PE):
        comma = "," if i < PE - 1 else ""
        lines.append(f"\tx[{i}]{comma} \\")
    lines.append("")

    # ----------------- SETUP_INTERPOLATOR_PRAGMAS -----------------

    lines.append("#define PRAGMA_SUB(x) _Pragma (#x) // source: https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/Using-Constants-with-Pragmas")
    lines.append("#define PRAGMA_HLS(x) PRAGMA_SUB(x)")
    lines.append("#define SETUP_INTERPOLATOR_PRAGMAS \\")
    for i in range(0, PE):
        lines.append(f"\tPRAGMA_HLS(HLS interface axis depth=524288 port=out_{i+1}) \\")
    lines.append("")

    # ----------------- SETUP_INTERPOLATOR_AIE_STARTER -----------------

    lines.append("#define SETUP_INTERPOLATOR_AIE_STARTER \\")

    for i in range (0, PE):
        lines.append(f"\tdata.range(7,0) = {i}; \\")
        lines.append(f"\tout_{i+1}.write(data); \\")
        lines.append(f"\tout_{i+1}.write(data); \\")
    lines.append("")

    # ----------------- SETUP_INTERPOLATOR_BODY -----------------

    lines.append("#define SETUP_INTERPOLATOR_BODY \\")

    ranges = ["RANGE_" + format(32*(i+1), "03d") + "_" + format(32*i, "03d") for i in range(0, BI)]
    output = ["out_" + str(i+1) for i in range(0, PE)]

    M = max(PE, BI)

    # iterates on chunks of 32
    for i in range(0, M):
        if i % BI == 0:
            lines.append("\tA = Left_in.read(); \\")
            lines.append("\tB = Right_in.read(); \\")
        out = output[i % PE]
        rng = ranges[i % BI]
        lines.append(f"\t{out}.write(A.range({rng})); \\")
        lines.append(f"\t{out}.write(B.range({rng})); \\")
    
    lines.append("\n")
    

    return lines


def compute_stream_policy(INT_PE):
    """
    Writer policy:
      - INT_PE <= 64: n_streams = INT_PE // 2, repetitions = 2
      - INT_PE >  64: n_streams = 32, repetitions = 2 * (INT_PE // 64)
    """
    if INT_PE <= 64:
        n_streams = INT_PE // 2
        repetitions = 2
    else:
        n_streams = 32
        repetitions = 2 * (INT_PE // 64)
    return n_streams, repetitions


# used to generate the writer_body.hpp file
def generate_read(INT_PE, BI):
    n_streams, repetitions = compute_stream_policy(INT_PE)

    lines = []
    lines.append("#pragma once")
    lines.append("// This file is generated by data_movers/movers_generator.py")
    lines.append(f"// INT_PE = {INT_PE}, n_streams = {n_streams}, repetitions = {repetitions}")
    lines.append("")

    lines.extend(generate_range_defines(BI))

    # ----------------- WRITER_SIGNATURE -----------------

    lines.append("")
    lines.append("#define WRITER_SIGNATURE \\")
    for i in range(n_streams):
        comma = "," if i < n_streams - 1 else ""
        lines.append(
            f"\thls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_{i+1}{comma} \\"
        )
    lines.append("")

    # ----------------- WRITER_TESTBENCH_CALL -----------------

    lines.append("#define WRITER_TESTBENCH_CALL(x) \\")
    for i in range(n_streams):
        comma = "," if i < n_streams - 1 else ""
        lines.append(f"\tx[{i}]{comma} \\")
    lines.append("")

    # ----------------- WRITER_PRAGMAS -----------------

    lines.append("#define PRAGMA_SUB(x) _Pragma (#x) // source: https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/Using-Constants-with-Pragmas")
    lines.append("#define PRAGMA_HLS(x) PRAGMA_SUB(x)")
    lines.append("#define WRITER_PRAGMAS \\")
    for i in range(n_streams):
        lines.append(f"\tPRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_{i+1}) \\")
    lines.append("")

    # ----------------- WRITER_BODY -----------------

    lines.append("#define WRITER_BODY \\")
    lines.append(f"\t/* policy: n_streams={n_streams}, repetitions={repetitions} */ \\")

    ranges = [
        "RANGE_" + format(32*(i+1), "03d") + "_" + format(32*i, "03d")
        for i in range(BI)
    ]

    # Each stream produces <repetitions> outputs
    # index = (i << INT_PE_EXPO) + (stream_idx * repetitions + rep_idx)
    for s in range(n_streams):
        lines.append(f"\t/* ---- Stream {s+1}/{n_streams} ---- */ \\")
        lines.append(f"\tap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_{s+1}; \\")
        for r in range(repetitions):
            linear = s * repetitions + r
            lines.append(f"\tap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_{s+1}_{r}; \\")
            lines.append(f"\tpixels_{s+1}_{r} = pixels_in_{s+1}.read(); \\")

            # pack BI chunks of 32 bits
            for k in range(BI):
                rng = ranges[k]
                lines.append(
                    f"\tpixels_mem_{s+1}.range({rng}) = pixels_{s+1}_{r}.range({rng}); \\"
                )

            lines.append(
                f"\tpixels_out[(i << INT_PE_EXPO) + {linear}] = pixels_mem_{s+1}; \\"
            )

        lines.append(f"\t/* -------------------------------- */ \\")

    lines.append("\n")
    return lines

if len(sys.argv) < 4:
    print("Usage: python3 movers_generator.py <INT_PE> <BITWIDTH> <HISTO_PE>")
    exit(1)

arg_IPE = int(sys.argv[1])
arg_BI = int(int(sys.argv[2]) / 32)
# arg_BI = int(64 / 32)
arg_HPE = int(sys.argv[3])

setup_interpolator_file = open("setup_interpolator_body.hpp", "w")
setup_interpolator_lines = generate_write(arg_IPE, arg_BI)
setup_interpolator_file.write("\n".join(setup_interpolator_lines))

# saturated_arg_IPE = 64 if arg_IPE > 64 else arg_IPE

writer_file = open("writer_body.hpp", "w")
writer_lines = generate_read(arg_IPE, arg_BI)
writer_file.write("\n".join(writer_lines))

