# MIT License
# Copyright (c) 2025
# Giuseppe Sorrentino, Paolo Salvatore Galfano, Davide Conficconi, Eleonora D'Arnese

import sys
import math


def macro(block_lines):

    if not block_lines:
        return []
    out = []
    for i, ln in enumerate(block_lines):
        if i < len(block_lines) - 1:
            out.append(ln.rstrip() + " \\")
        else:
            out.append(ln.rstrip())
    return out


def generate_signature_and_pragmas(IPE):
    lines = []
    lines.append("#pragma once")
    lines.append("// This file is generated by setup_mi_generator.py")
    lines.append(f"// INT_PE = {IPE}, n_streams and repetitions computed automatically")
    lines.append("")

    # compute INT_PE_EXPO
    if IPE & (IPE - 1) != 0:
        print(f"[setup_mi_generator] WARNING: INT_PE={IPE} is not a power of two. Using INT_PE_EXPO=floor(log2(INT_PE)).")
    int_pe_expo = int(math.log2(IPE))
    lines.append(f"#define INT_PE_EXPO {int_pe_expo}")
    lines.append("")

    # Add macro RANGE
    lines.append("#define RANGE_016_000 127, 0")
    lines.append("#define RANGE_032_016 255, 128")
    lines.append("#define RANGE_WRITER_032_000 255, 0")
    lines.append("")

    # --- Compute Streams and Repetitions ---
    if IPE <= 64:
        n_streams = IPE // 2
        repetitions = 2
    else:
        n_streams = 32
        repetitions = 2 * (IPE // 64)

    # --- SIGNATURE ---
    sig = ["#define SETUP_MI_SIGNATURE"]
    for i in range(n_streams):
        comma = "," if i < n_streams - 1 else ""
        sig.append(
            f"\thls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_{i+1}{comma}"
        )
    lines += macro(sig)
    lines.append("")

    # --- TESTBENCH CALL ---
    tb = ["#define SETUP_MI_TESTBENCH_CALL(x)"]
    for i in range(n_streams):
        comma = "," if i < n_streams - 1 else ""
        tb.append(f"\tx[{i}]{comma}")
    lines += macro(tb)
    lines.append("")

    # --- PRAGMA helpers (no backslash) ---
    lines.append("#define PRAGMA_SUB(x) _Pragma (#x)")
    lines.append("#define PRAGMA_HLS(x) PRAGMA_SUB(x)")
    lines.append("")

    # --- PRAGMAS macro ---
    pr = ["#define SETUP_MI_PRAGMAS"]
    for i in range(n_streams):
        pr.append(f"\tPRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_{i+1})")
    lines += macro(pr)
    lines.append("")

    return lines, n_streams, repetitions


def generate_volume_macro():
    vol = [
        "/* The last division is due to the unrolling factor computed at compile time */",
        "#define SETUP_MI_VOLUME(n_row, n_col)",
        "const int unrolling_factor_expo = 0;",
        "const int VOLUME_withoutDepth = (((n_row * n_col) >> INT_PE_EXPO_SATURATED) >> 5) >> unrolling_factor_expo;",
    ]
    return macro(vol) + [""]


def generate_body(n_streams, repetitions):
    """
    Affine write in memory with explicit shift to compute the correct address for each stream and repetition.:
      index = (i << INT_PE_EXPO) + (stream_idx * repetitions + rep_idx)
    """
    body = [
        "#define SETUP_MI_BODY",
        f"\t/* Auto-generated pixel reading and merging logic (AFFINE memory writes with shift) */",
        f"\t/* n_streams = {n_streams} */",
        f"\t/* repetitions = {repetitions} */",
        "\t/* index = (i << INT_PE_EXPO) + (stream_idx * repetitions + rep_idx) */",
    ]

    for s in range(n_streams):
        body.append(f"\t/* ---- Stream {s+1}/{n_streams} ---- */")
        body.append(f"\tap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_{s+1};")
        for r in range(repetitions):
            linear = s * repetitions + r
            body.append(f"\tap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_{s+1}_{r};")
            body.append(f"\tpixels_{s+1}_{r} = pixels_in_{s+1}.read();")
            body.append(f"\tpixels_out.write(pixels_{s+1}_{r}.range(RANGE_016_000));")
            body.append(f"\tpixels_out.write(pixels_{s+1}_{r}.range(RANGE_032_016));")
            body.append(f"\tpixels_mem_{s+1}.range(RANGE_WRITER_032_000) = pixels_{s+1}_{r};")
            body.append(f"\tpixels_out_mem[(i << INT_PE_EXPO) + {linear}] = pixels_mem_{s+1};")
        body.append(f"\t/* ---------------------------------------------- */")

    return macro(body) + [""]


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 setup_mi_generator.py <INT_PE>")
        sys.exit(1)

    IPE = int(sys.argv[1])

    signature_lines, n_streams, repetitions = generate_signature_and_pragmas(IPE)
    volume_lines = generate_volume_macro()
    body_lines = generate_body(n_streams, repetitions)

    output_file = "setup_mi_body.hpp"
    with open(output_file, "w") as f:
        f.write("\n".join(signature_lines + volume_lines + body_lines))
        f.write("\n")

    print(f"[setup_mi_generator] Generated {output_file} for INT_PE={IPE}")
    print(f" -> Streams: {n_streams}, repetitions: {repetitions}")
    print(f" -> Using INT_PE_EXPO = {int(math.log2(IPE))}")


if __name__ == "__main__":
    main()
