#pragma once
// This file is generated by data_movers/movers_generator.py
#define RANGE_016_000 127, 0
#define RANGE_032_016 255, 128
#define RANGE_WRITER_032_000 255, 0

#define SETUP_MI_SIGNATURE                                                  \
    hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_1,      \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_2,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_3,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_4,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_5,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_6,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_7,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_8,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_9,  \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_10, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_11, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_12, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_13, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_14, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_15, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_16, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_17, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_18, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_19, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_20, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_21, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_22, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_23, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_24, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_25, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_26, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_27, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_28, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_29, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_30, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_31, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_32, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_33, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_34, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_35, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_36, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_37, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_38, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_39, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_40, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_41, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_42, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_43, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_44, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_45, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_46, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_47, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_48, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_49, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_50, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_51, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_52, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_53, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_54, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_55, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_56, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_57, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_58, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_59, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_60, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_61, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_62, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_63, \
        hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>&pixels_in_64

#define SETUP_MI_TESTBENCH_CALL(x)                                                                               \
    x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9], x[10], x[11], x[12], x[13], x[14], x[15], x[16], \
        x[17], x[18], x[19], x[20], x[21], x[22], x[23], x[24], x[25], x[26], x[27], x[28], x[29], x[30], x[31], \
        x[32], x[33], x[34], x[35], x[36], x[37], x[38], x[39], x[40], x[41], x[42], x[43], x[44], x[45], x[46], \
        x[47], x[48], x[49], x[50], x[51], x[52], x[53], x[54], x[55], x[56], x[57], x[58], x[59], x[60], x[61], \
        x[62], x[63]

#define PRAGMA_SUB(x) \
    _Pragma(#x)  // source: https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/Using-Constants-with-Pragmas
#define PRAGMA_HLS(x) PRAGMA_SUB(x)
#define SETUP_MI_PRAGMAS                                              \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_1)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_2)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_3)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_4)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_5)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_6)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_7)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_8)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_9)  \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_10) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_11) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_12) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_13) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_14) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_15) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_16) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_17) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_18) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_19) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_20) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_21) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_22) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_23) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_24) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_25) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_26) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_27) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_28) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_29) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_30) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_31) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_32) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_33) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_34) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_35) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_36) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_37) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_38) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_39) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_40) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_41) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_42) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_43) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_44) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_45) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_46) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_47) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_48) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_49) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_50) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_51) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_52) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_53) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_54) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_55) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_56) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_57) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_58) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_59) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_60) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_61) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_62) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_63) \
    PRAGMA_HLS(HLS interface axis depth = 524288 port = pixels_in_64)

// The last division is due to the unrolling factor computer at compile time
#define SETUP_MI_VOLUME(n_row, n_col)    \
    const int unrolling_factor_expo = 0; \
    const int VOLUME_withoutDepth = (((n_row * n_col) >> INT_PE_EXPO_SATURATED) >> (5)) >> unrolling_factor_expo;

#define SETUP_MI_BODY                                            \
    /* ---- ---- n 0/0 | ipe 0/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_1_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_1_0;         \
    pixels_1_0 = pixels_in_1.read();                             \
    pixels_out.write(pixels_1_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_1_0.range(RANGE_032_016));           \
    pixels_mem_1_0.range(RANGE_WRITER_032_000) = pixels_1_0;     \
    pixels_out_mem[(i << 7) + 0] = pixels_mem_1_0;               \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_1_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_1_1;         \
    pixels_1_1 = pixels_in_1.read();                             \
    pixels_out.write(pixels_1_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_1_1.range(RANGE_032_016));           \
    pixels_mem_1_1.range(RANGE_WRITER_032_000) = pixels_1_1;     \
    pixels_out_mem[(i << 7) + 1] = pixels_mem_1_1;               \
    /* ---- ---- n 0/0 | ipe 1/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_2_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_2_0;         \
    pixels_2_0 = pixels_in_2.read();                             \
    pixels_out.write(pixels_2_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_2_0.range(RANGE_032_016));           \
    pixels_mem_2_0.range(RANGE_WRITER_032_000) = pixels_2_0;     \
    pixels_out_mem[(i << 7) + 2] = pixels_mem_2_0;               \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_2_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_2_1;         \
    pixels_2_1 = pixels_in_2.read();                             \
    pixels_out.write(pixels_2_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_2_1.range(RANGE_032_016));           \
    pixels_mem_2_1.range(RANGE_WRITER_032_000) = pixels_2_1;     \
    pixels_out_mem[(i << 7) + 3] = pixels_mem_2_1;               \
    /* ---- ---- n 0/0 | ipe 2/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_3_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_3_0;         \
    pixels_3_0 = pixels_in_3.read();                             \
    pixels_out.write(pixels_3_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_3_0.range(RANGE_032_016));           \
    pixels_mem_3_0.range(RANGE_WRITER_032_000) = pixels_3_0;     \
    pixels_out_mem[(i << 7) + 4] = pixels_mem_3_0;               \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_3_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_3_1;         \
    pixels_3_1 = pixels_in_3.read();                             \
    pixels_out.write(pixels_3_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_3_1.range(RANGE_032_016));           \
    pixels_mem_3_1.range(RANGE_WRITER_032_000) = pixels_3_1;     \
    pixels_out_mem[(i << 7) + 5] = pixels_mem_3_1;               \
    /* ---- ---- n 0/0 | ipe 3/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_4_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_4_0;         \
    pixels_4_0 = pixels_in_4.read();                             \
    pixels_out.write(pixels_4_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_4_0.range(RANGE_032_016));           \
    pixels_mem_4_0.range(RANGE_WRITER_032_000) = pixels_4_0;     \
    pixels_out_mem[(i << 7) + 6] = pixels_mem_4_0;               \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_4_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_4_1;         \
    pixels_4_1 = pixels_in_4.read();                             \
    pixels_out.write(pixels_4_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_4_1.range(RANGE_032_016));           \
    pixels_mem_4_1.range(RANGE_WRITER_032_000) = pixels_4_1;     \
    pixels_out_mem[(i << 7) + 7] = pixels_mem_4_1;               \
    /* ---- ---- n 0/0 | ipe 4/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_5_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_5_0;         \
    pixels_5_0 = pixels_in_5.read();                             \
    pixels_out.write(pixels_5_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_5_0.range(RANGE_032_016));           \
    pixels_mem_5_0.range(RANGE_WRITER_032_000) = pixels_5_0;     \
    pixels_out_mem[(i << 7) + 8] = pixels_mem_5_0;               \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_5_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_5_1;         \
    pixels_5_1 = pixels_in_5.read();                             \
    pixels_out.write(pixels_5_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_5_1.range(RANGE_032_016));           \
    pixels_mem_5_1.range(RANGE_WRITER_032_000) = pixels_5_1;     \
    pixels_out_mem[(i << 7) + 9] = pixels_mem_5_1;               \
    /* ---- ---- n 0/0 | ipe 5/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_6_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_6_0;         \
    pixels_6_0 = pixels_in_6.read();                             \
    pixels_out.write(pixels_6_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_6_0.range(RANGE_032_016));           \
    pixels_mem_6_0.range(RANGE_WRITER_032_000) = pixels_6_0;     \
    pixels_out_mem[(i << 7) + 10] = pixels_mem_6_0;              \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_6_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_6_1;         \
    pixels_6_1 = pixels_in_6.read();                             \
    pixels_out.write(pixels_6_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_6_1.range(RANGE_032_016));           \
    pixels_mem_6_1.range(RANGE_WRITER_032_000) = pixels_6_1;     \
    pixels_out_mem[(i << 7) + 11] = pixels_mem_6_1;              \
    /* ---- ---- n 0/0 | ipe 6/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_7_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_7_0;         \
    pixels_7_0 = pixels_in_7.read();                             \
    pixels_out.write(pixels_7_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_7_0.range(RANGE_032_016));           \
    pixels_mem_7_0.range(RANGE_WRITER_032_000) = pixels_7_0;     \
    pixels_out_mem[(i << 7) + 12] = pixels_mem_7_0;              \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_7_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_7_1;         \
    pixels_7_1 = pixels_in_7.read();                             \
    pixels_out.write(pixels_7_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_7_1.range(RANGE_032_016));           \
    pixels_mem_7_1.range(RANGE_WRITER_032_000) = pixels_7_1;     \
    pixels_out_mem[(i << 7) + 13] = pixels_mem_7_1;              \
    /* ---- ---- n 0/0 | ipe 7/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_8_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_8_0;         \
    pixels_8_0 = pixels_in_8.read();                             \
    pixels_out.write(pixels_8_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_8_0.range(RANGE_032_016));           \
    pixels_mem_8_0.range(RANGE_WRITER_032_000) = pixels_8_0;     \
    pixels_out_mem[(i << 7) + 14] = pixels_mem_8_0;              \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_8_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_8_1;         \
    pixels_8_1 = pixels_in_8.read();                             \
    pixels_out.write(pixels_8_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_8_1.range(RANGE_032_016));           \
    pixels_mem_8_1.range(RANGE_WRITER_032_000) = pixels_8_1;     \
    pixels_out_mem[(i << 7) + 15] = pixels_mem_8_1;              \
    /* ---- ---- n 0/0 | ipe 8/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_9_0;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_9_0;         \
    pixels_9_0 = pixels_in_9.read();                             \
    pixels_out.write(pixels_9_0.range(RANGE_016_000));           \
    pixels_out.write(pixels_9_0.range(RANGE_032_016));           \
    pixels_mem_9_0.range(RANGE_WRITER_032_000) = pixels_9_0;     \
    pixels_out_mem[(i << 7) + 16] = pixels_mem_9_0;              \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_9_1;         \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_9_1;         \
    pixels_9_1 = pixels_in_9.read();                             \
    pixels_out.write(pixels_9_1.range(RANGE_016_000));           \
    pixels_out.write(pixels_9_1.range(RANGE_032_016));           \
    pixels_mem_9_1.range(RANGE_WRITER_032_000) = pixels_9_1;     \
    pixels_out_mem[(i << 7) + 17] = pixels_mem_9_1;              \
    /* ---- ---- n 0/0 | ipe 9/63 (saturated=True) ---- ---- */  \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_10_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_10_0;        \
    pixels_10_0 = pixels_in_10.read();                           \
    pixels_out.write(pixels_10_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_10_0.range(RANGE_032_016));          \
    pixels_mem_10_0.range(RANGE_WRITER_032_000) = pixels_10_0;   \
    pixels_out_mem[(i << 7) + 18] = pixels_mem_10_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_10_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_10_1;        \
    pixels_10_1 = pixels_in_10.read();                           \
    pixels_out.write(pixels_10_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_10_1.range(RANGE_032_016));          \
    pixels_mem_10_1.range(RANGE_WRITER_032_000) = pixels_10_1;   \
    pixels_out_mem[(i << 7) + 19] = pixels_mem_10_1;             \
    /* ---- ---- n 0/0 | ipe 10/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_11_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_11_0;        \
    pixels_11_0 = pixels_in_11.read();                           \
    pixels_out.write(pixels_11_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_11_0.range(RANGE_032_016));          \
    pixels_mem_11_0.range(RANGE_WRITER_032_000) = pixels_11_0;   \
    pixels_out_mem[(i << 7) + 20] = pixels_mem_11_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_11_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_11_1;        \
    pixels_11_1 = pixels_in_11.read();                           \
    pixels_out.write(pixels_11_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_11_1.range(RANGE_032_016));          \
    pixels_mem_11_1.range(RANGE_WRITER_032_000) = pixels_11_1;   \
    pixels_out_mem[(i << 7) + 21] = pixels_mem_11_1;             \
    /* ---- ---- n 0/0 | ipe 11/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_12_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_12_0;        \
    pixels_12_0 = pixels_in_12.read();                           \
    pixels_out.write(pixels_12_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_12_0.range(RANGE_032_016));          \
    pixels_mem_12_0.range(RANGE_WRITER_032_000) = pixels_12_0;   \
    pixels_out_mem[(i << 7) + 22] = pixels_mem_12_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_12_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_12_1;        \
    pixels_12_1 = pixels_in_12.read();                           \
    pixels_out.write(pixels_12_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_12_1.range(RANGE_032_016));          \
    pixels_mem_12_1.range(RANGE_WRITER_032_000) = pixels_12_1;   \
    pixels_out_mem[(i << 7) + 23] = pixels_mem_12_1;             \
    /* ---- ---- n 0/0 | ipe 12/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_13_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_13_0;        \
    pixels_13_0 = pixels_in_13.read();                           \
    pixels_out.write(pixels_13_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_13_0.range(RANGE_032_016));          \
    pixels_mem_13_0.range(RANGE_WRITER_032_000) = pixels_13_0;   \
    pixels_out_mem[(i << 7) + 24] = pixels_mem_13_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_13_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_13_1;        \
    pixels_13_1 = pixels_in_13.read();                           \
    pixels_out.write(pixels_13_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_13_1.range(RANGE_032_016));          \
    pixels_mem_13_1.range(RANGE_WRITER_032_000) = pixels_13_1;   \
    pixels_out_mem[(i << 7) + 25] = pixels_mem_13_1;             \
    /* ---- ---- n 0/0 | ipe 13/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_14_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_14_0;        \
    pixels_14_0 = pixels_in_14.read();                           \
    pixels_out.write(pixels_14_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_14_0.range(RANGE_032_016));          \
    pixels_mem_14_0.range(RANGE_WRITER_032_000) = pixels_14_0;   \
    pixels_out_mem[(i << 7) + 26] = pixels_mem_14_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_14_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_14_1;        \
    pixels_14_1 = pixels_in_14.read();                           \
    pixels_out.write(pixels_14_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_14_1.range(RANGE_032_016));          \
    pixels_mem_14_1.range(RANGE_WRITER_032_000) = pixels_14_1;   \
    pixels_out_mem[(i << 7) + 27] = pixels_mem_14_1;             \
    /* ---- ---- n 0/0 | ipe 14/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_15_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_15_0;        \
    pixels_15_0 = pixels_in_15.read();                           \
    pixels_out.write(pixels_15_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_15_0.range(RANGE_032_016));          \
    pixels_mem_15_0.range(RANGE_WRITER_032_000) = pixels_15_0;   \
    pixels_out_mem[(i << 7) + 28] = pixels_mem_15_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_15_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_15_1;        \
    pixels_15_1 = pixels_in_15.read();                           \
    pixels_out.write(pixels_15_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_15_1.range(RANGE_032_016));          \
    pixels_mem_15_1.range(RANGE_WRITER_032_000) = pixels_15_1;   \
    pixels_out_mem[(i << 7) + 29] = pixels_mem_15_1;             \
    /* ---- ---- n 0/0 | ipe 15/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_16_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_16_0;        \
    pixels_16_0 = pixels_in_16.read();                           \
    pixels_out.write(pixels_16_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_16_0.range(RANGE_032_016));          \
    pixels_mem_16_0.range(RANGE_WRITER_032_000) = pixels_16_0;   \
    pixels_out_mem[(i << 7) + 30] = pixels_mem_16_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_16_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_16_1;        \
    pixels_16_1 = pixels_in_16.read();                           \
    pixels_out.write(pixels_16_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_16_1.range(RANGE_032_016));          \
    pixels_mem_16_1.range(RANGE_WRITER_032_000) = pixels_16_1;   \
    pixels_out_mem[(i << 7) + 31] = pixels_mem_16_1;             \
    /* ---- ---- n 0/0 | ipe 16/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_17_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_17_0;        \
    pixels_17_0 = pixels_in_17.read();                           \
    pixels_out.write(pixels_17_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_17_0.range(RANGE_032_016));          \
    pixels_mem_17_0.range(RANGE_WRITER_032_000) = pixels_17_0;   \
    pixels_out_mem[(i << 7) + 32] = pixels_mem_17_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_17_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_17_1;        \
    pixels_17_1 = pixels_in_17.read();                           \
    pixels_out.write(pixels_17_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_17_1.range(RANGE_032_016));          \
    pixels_mem_17_1.range(RANGE_WRITER_032_000) = pixels_17_1;   \
    pixels_out_mem[(i << 7) + 33] = pixels_mem_17_1;             \
    /* ---- ---- n 0/0 | ipe 17/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_18_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_18_0;        \
    pixels_18_0 = pixels_in_18.read();                           \
    pixels_out.write(pixels_18_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_18_0.range(RANGE_032_016));          \
    pixels_mem_18_0.range(RANGE_WRITER_032_000) = pixels_18_0;   \
    pixels_out_mem[(i << 7) + 34] = pixels_mem_18_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_18_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_18_1;        \
    pixels_18_1 = pixels_in_18.read();                           \
    pixels_out.write(pixels_18_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_18_1.range(RANGE_032_016));          \
    pixels_mem_18_1.range(RANGE_WRITER_032_000) = pixels_18_1;   \
    pixels_out_mem[(i << 7) + 35] = pixels_mem_18_1;             \
    /* ---- ---- n 0/0 | ipe 18/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_19_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_19_0;        \
    pixels_19_0 = pixels_in_19.read();                           \
    pixels_out.write(pixels_19_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_19_0.range(RANGE_032_016));          \
    pixels_mem_19_0.range(RANGE_WRITER_032_000) = pixels_19_0;   \
    pixels_out_mem[(i << 7) + 36] = pixels_mem_19_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_19_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_19_1;        \
    pixels_19_1 = pixels_in_19.read();                           \
    pixels_out.write(pixels_19_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_19_1.range(RANGE_032_016));          \
    pixels_mem_19_1.range(RANGE_WRITER_032_000) = pixels_19_1;   \
    pixels_out_mem[(i << 7) + 37] = pixels_mem_19_1;             \
    /* ---- ---- n 0/0 | ipe 19/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_20_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_20_0;        \
    pixels_20_0 = pixels_in_20.read();                           \
    pixels_out.write(pixels_20_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_20_0.range(RANGE_032_016));          \
    pixels_mem_20_0.range(RANGE_WRITER_032_000) = pixels_20_0;   \
    pixels_out_mem[(i << 7) + 38] = pixels_mem_20_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_20_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_20_1;        \
    pixels_20_1 = pixels_in_20.read();                           \
    pixels_out.write(pixels_20_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_20_1.range(RANGE_032_016));          \
    pixels_mem_20_1.range(RANGE_WRITER_032_000) = pixels_20_1;   \
    pixels_out_mem[(i << 7) + 39] = pixels_mem_20_1;             \
    /* ---- ---- n 0/0 | ipe 20/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_21_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_21_0;        \
    pixels_21_0 = pixels_in_21.read();                           \
    pixels_out.write(pixels_21_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_21_0.range(RANGE_032_016));          \
    pixels_mem_21_0.range(RANGE_WRITER_032_000) = pixels_21_0;   \
    pixels_out_mem[(i << 7) + 40] = pixels_mem_21_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_21_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_21_1;        \
    pixels_21_1 = pixels_in_21.read();                           \
    pixels_out.write(pixels_21_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_21_1.range(RANGE_032_016));          \
    pixels_mem_21_1.range(RANGE_WRITER_032_000) = pixels_21_1;   \
    pixels_out_mem[(i << 7) + 41] = pixels_mem_21_1;             \
    /* ---- ---- n 0/0 | ipe 21/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_22_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_22_0;        \
    pixels_22_0 = pixels_in_22.read();                           \
    pixels_out.write(pixels_22_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_22_0.range(RANGE_032_016));          \
    pixels_mem_22_0.range(RANGE_WRITER_032_000) = pixels_22_0;   \
    pixels_out_mem[(i << 7) + 42] = pixels_mem_22_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_22_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_22_1;        \
    pixels_22_1 = pixels_in_22.read();                           \
    pixels_out.write(pixels_22_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_22_1.range(RANGE_032_016));          \
    pixels_mem_22_1.range(RANGE_WRITER_032_000) = pixels_22_1;   \
    pixels_out_mem[(i << 7) + 43] = pixels_mem_22_1;             \
    /* ---- ---- n 0/0 | ipe 22/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_23_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_23_0;        \
    pixels_23_0 = pixels_in_23.read();                           \
    pixels_out.write(pixels_23_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_23_0.range(RANGE_032_016));          \
    pixels_mem_23_0.range(RANGE_WRITER_032_000) = pixels_23_0;   \
    pixels_out_mem[(i << 7) + 44] = pixels_mem_23_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_23_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_23_1;        \
    pixels_23_1 = pixels_in_23.read();                           \
    pixels_out.write(pixels_23_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_23_1.range(RANGE_032_016));          \
    pixels_mem_23_1.range(RANGE_WRITER_032_000) = pixels_23_1;   \
    pixels_out_mem[(i << 7) + 45] = pixels_mem_23_1;             \
    /* ---- ---- n 0/0 | ipe 23/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_24_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_24_0;        \
    pixels_24_0 = pixels_in_24.read();                           \
    pixels_out.write(pixels_24_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_24_0.range(RANGE_032_016));          \
    pixels_mem_24_0.range(RANGE_WRITER_032_000) = pixels_24_0;   \
    pixels_out_mem[(i << 7) + 46] = pixels_mem_24_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_24_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_24_1;        \
    pixels_24_1 = pixels_in_24.read();                           \
    pixels_out.write(pixels_24_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_24_1.range(RANGE_032_016));          \
    pixels_mem_24_1.range(RANGE_WRITER_032_000) = pixels_24_1;   \
    pixels_out_mem[(i << 7) + 47] = pixels_mem_24_1;             \
    /* ---- ---- n 0/0 | ipe 24/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_25_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_25_0;        \
    pixels_25_0 = pixels_in_25.read();                           \
    pixels_out.write(pixels_25_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_25_0.range(RANGE_032_016));          \
    pixels_mem_25_0.range(RANGE_WRITER_032_000) = pixels_25_0;   \
    pixels_out_mem[(i << 7) + 48] = pixels_mem_25_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_25_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_25_1;        \
    pixels_25_1 = pixels_in_25.read();                           \
    pixels_out.write(pixels_25_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_25_1.range(RANGE_032_016));          \
    pixels_mem_25_1.range(RANGE_WRITER_032_000) = pixels_25_1;   \
    pixels_out_mem[(i << 7) + 49] = pixels_mem_25_1;             \
    /* ---- ---- n 0/0 | ipe 25/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_26_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_26_0;        \
    pixels_26_0 = pixels_in_26.read();                           \
    pixels_out.write(pixels_26_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_26_0.range(RANGE_032_016));          \
    pixels_mem_26_0.range(RANGE_WRITER_032_000) = pixels_26_0;   \
    pixels_out_mem[(i << 7) + 50] = pixels_mem_26_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_26_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_26_1;        \
    pixels_26_1 = pixels_in_26.read();                           \
    pixels_out.write(pixels_26_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_26_1.range(RANGE_032_016));          \
    pixels_mem_26_1.range(RANGE_WRITER_032_000) = pixels_26_1;   \
    pixels_out_mem[(i << 7) + 51] = pixels_mem_26_1;             \
    /* ---- ---- n 0/0 | ipe 26/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_27_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_27_0;        \
    pixels_27_0 = pixels_in_27.read();                           \
    pixels_out.write(pixels_27_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_27_0.range(RANGE_032_016));          \
    pixels_mem_27_0.range(RANGE_WRITER_032_000) = pixels_27_0;   \
    pixels_out_mem[(i << 7) + 52] = pixels_mem_27_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_27_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_27_1;        \
    pixels_27_1 = pixels_in_27.read();                           \
    pixels_out.write(pixels_27_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_27_1.range(RANGE_032_016));          \
    pixels_mem_27_1.range(RANGE_WRITER_032_000) = pixels_27_1;   \
    pixels_out_mem[(i << 7) + 53] = pixels_mem_27_1;             \
    /* ---- ---- n 0/0 | ipe 27/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_28_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_28_0;        \
    pixels_28_0 = pixels_in_28.read();                           \
    pixels_out.write(pixels_28_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_28_0.range(RANGE_032_016));          \
    pixels_mem_28_0.range(RANGE_WRITER_032_000) = pixels_28_0;   \
    pixels_out_mem[(i << 7) + 54] = pixels_mem_28_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_28_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_28_1;        \
    pixels_28_1 = pixels_in_28.read();                           \
    pixels_out.write(pixels_28_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_28_1.range(RANGE_032_016));          \
    pixels_mem_28_1.range(RANGE_WRITER_032_000) = pixels_28_1;   \
    pixels_out_mem[(i << 7) + 55] = pixels_mem_28_1;             \
    /* ---- ---- n 0/0 | ipe 28/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_29_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_29_0;        \
    pixels_29_0 = pixels_in_29.read();                           \
    pixels_out.write(pixels_29_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_29_0.range(RANGE_032_016));          \
    pixels_mem_29_0.range(RANGE_WRITER_032_000) = pixels_29_0;   \
    pixels_out_mem[(i << 7) + 56] = pixels_mem_29_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_29_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_29_1;        \
    pixels_29_1 = pixels_in_29.read();                           \
    pixels_out.write(pixels_29_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_29_1.range(RANGE_032_016));          \
    pixels_mem_29_1.range(RANGE_WRITER_032_000) = pixels_29_1;   \
    pixels_out_mem[(i << 7) + 57] = pixels_mem_29_1;             \
    /* ---- ---- n 0/0 | ipe 29/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_30_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_30_0;        \
    pixels_30_0 = pixels_in_30.read();                           \
    pixels_out.write(pixels_30_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_30_0.range(RANGE_032_016));          \
    pixels_mem_30_0.range(RANGE_WRITER_032_000) = pixels_30_0;   \
    pixels_out_mem[(i << 7) + 58] = pixels_mem_30_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_30_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_30_1;        \
    pixels_30_1 = pixels_in_30.read();                           \
    pixels_out.write(pixels_30_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_30_1.range(RANGE_032_016));          \
    pixels_mem_30_1.range(RANGE_WRITER_032_000) = pixels_30_1;   \
    pixels_out_mem[(i << 7) + 59] = pixels_mem_30_1;             \
    /* ---- ---- n 0/0 | ipe 30/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_31_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_31_0;        \
    pixels_31_0 = pixels_in_31.read();                           \
    pixels_out.write(pixels_31_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_31_0.range(RANGE_032_016));          \
    pixels_mem_31_0.range(RANGE_WRITER_032_000) = pixels_31_0;   \
    pixels_out_mem[(i << 7) + 60] = pixels_mem_31_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_31_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_31_1;        \
    pixels_31_1 = pixels_in_31.read();                           \
    pixels_out.write(pixels_31_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_31_1.range(RANGE_032_016));          \
    pixels_mem_31_1.range(RANGE_WRITER_032_000) = pixels_31_1;   \
    pixels_out_mem[(i << 7) + 61] = pixels_mem_31_1;             \
    /* ---- ---- n 0/0 | ipe 31/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_32_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_32_0;        \
    pixels_32_0 = pixels_in_32.read();                           \
    pixels_out.write(pixels_32_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_32_0.range(RANGE_032_016));          \
    pixels_mem_32_0.range(RANGE_WRITER_032_000) = pixels_32_0;   \
    pixels_out_mem[(i << 7) + 62] = pixels_mem_32_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_32_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_32_1;        \
    pixels_32_1 = pixels_in_32.read();                           \
    pixels_out.write(pixels_32_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_32_1.range(RANGE_032_016));          \
    pixels_mem_32_1.range(RANGE_WRITER_032_000) = pixels_32_1;   \
    pixels_out_mem[(i << 7) + 63] = pixels_mem_32_1;             \
    /* ---- ---- n 0/0 | ipe 32/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_33_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_33_0;        \
    pixels_33_0 = pixels_in_33.read();                           \
    pixels_out.write(pixels_33_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_33_0.range(RANGE_032_016));          \
    pixels_mem_33_0.range(RANGE_WRITER_032_000) = pixels_33_0;   \
    pixels_out_mem[(i << 7) + 64] = pixels_mem_33_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_33_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_33_1;        \
    pixels_33_1 = pixels_in_33.read();                           \
    pixels_out.write(pixels_33_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_33_1.range(RANGE_032_016));          \
    pixels_mem_33_1.range(RANGE_WRITER_032_000) = pixels_33_1;   \
    pixels_out_mem[(i << 7) + 65] = pixels_mem_33_1;             \
    /* ---- ---- n 0/0 | ipe 33/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_34_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_34_0;        \
    pixels_34_0 = pixels_in_34.read();                           \
    pixels_out.write(pixels_34_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_34_0.range(RANGE_032_016));          \
    pixels_mem_34_0.range(RANGE_WRITER_032_000) = pixels_34_0;   \
    pixels_out_mem[(i << 7) + 66] = pixels_mem_34_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_34_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_34_1;        \
    pixels_34_1 = pixels_in_34.read();                           \
    pixels_out.write(pixels_34_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_34_1.range(RANGE_032_016));          \
    pixels_mem_34_1.range(RANGE_WRITER_032_000) = pixels_34_1;   \
    pixels_out_mem[(i << 7) + 67] = pixels_mem_34_1;             \
    /* ---- ---- n 0/0 | ipe 34/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_35_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_35_0;        \
    pixels_35_0 = pixels_in_35.read();                           \
    pixels_out.write(pixels_35_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_35_0.range(RANGE_032_016));          \
    pixels_mem_35_0.range(RANGE_WRITER_032_000) = pixels_35_0;   \
    pixels_out_mem[(i << 7) + 68] = pixels_mem_35_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_35_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_35_1;        \
    pixels_35_1 = pixels_in_35.read();                           \
    pixels_out.write(pixels_35_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_35_1.range(RANGE_032_016));          \
    pixels_mem_35_1.range(RANGE_WRITER_032_000) = pixels_35_1;   \
    pixels_out_mem[(i << 7) + 69] = pixels_mem_35_1;             \
    /* ---- ---- n 0/0 | ipe 35/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_36_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_36_0;        \
    pixels_36_0 = pixels_in_36.read();                           \
    pixels_out.write(pixels_36_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_36_0.range(RANGE_032_016));          \
    pixels_mem_36_0.range(RANGE_WRITER_032_000) = pixels_36_0;   \
    pixels_out_mem[(i << 7) + 70] = pixels_mem_36_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_36_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_36_1;        \
    pixels_36_1 = pixels_in_36.read();                           \
    pixels_out.write(pixels_36_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_36_1.range(RANGE_032_016));          \
    pixels_mem_36_1.range(RANGE_WRITER_032_000) = pixels_36_1;   \
    pixels_out_mem[(i << 7) + 71] = pixels_mem_36_1;             \
    /* ---- ---- n 0/0 | ipe 36/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_37_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_37_0;        \
    pixels_37_0 = pixels_in_37.read();                           \
    pixels_out.write(pixels_37_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_37_0.range(RANGE_032_016));          \
    pixels_mem_37_0.range(RANGE_WRITER_032_000) = pixels_37_0;   \
    pixels_out_mem[(i << 7) + 72] = pixels_mem_37_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_37_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_37_1;        \
    pixels_37_1 = pixels_in_37.read();                           \
    pixels_out.write(pixels_37_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_37_1.range(RANGE_032_016));          \
    pixels_mem_37_1.range(RANGE_WRITER_032_000) = pixels_37_1;   \
    pixels_out_mem[(i << 7) + 73] = pixels_mem_37_1;             \
    /* ---- ---- n 0/0 | ipe 37/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_38_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_38_0;        \
    pixels_38_0 = pixels_in_38.read();                           \
    pixels_out.write(pixels_38_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_38_0.range(RANGE_032_016));          \
    pixels_mem_38_0.range(RANGE_WRITER_032_000) = pixels_38_0;   \
    pixels_out_mem[(i << 7) + 74] = pixels_mem_38_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_38_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_38_1;        \
    pixels_38_1 = pixels_in_38.read();                           \
    pixels_out.write(pixels_38_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_38_1.range(RANGE_032_016));          \
    pixels_mem_38_1.range(RANGE_WRITER_032_000) = pixels_38_1;   \
    pixels_out_mem[(i << 7) + 75] = pixels_mem_38_1;             \
    /* ---- ---- n 0/0 | ipe 38/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_39_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_39_0;        \
    pixels_39_0 = pixels_in_39.read();                           \
    pixels_out.write(pixels_39_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_39_0.range(RANGE_032_016));          \
    pixels_mem_39_0.range(RANGE_WRITER_032_000) = pixels_39_0;   \
    pixels_out_mem[(i << 7) + 76] = pixels_mem_39_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_39_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_39_1;        \
    pixels_39_1 = pixels_in_39.read();                           \
    pixels_out.write(pixels_39_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_39_1.range(RANGE_032_016));          \
    pixels_mem_39_1.range(RANGE_WRITER_032_000) = pixels_39_1;   \
    pixels_out_mem[(i << 7) + 77] = pixels_mem_39_1;             \
    /* ---- ---- n 0/0 | ipe 39/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_40_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_40_0;        \
    pixels_40_0 = pixels_in_40.read();                           \
    pixels_out.write(pixels_40_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_40_0.range(RANGE_032_016));          \
    pixels_mem_40_0.range(RANGE_WRITER_032_000) = pixels_40_0;   \
    pixels_out_mem[(i << 7) + 78] = pixels_mem_40_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_40_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_40_1;        \
    pixels_40_1 = pixels_in_40.read();                           \
    pixels_out.write(pixels_40_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_40_1.range(RANGE_032_016));          \
    pixels_mem_40_1.range(RANGE_WRITER_032_000) = pixels_40_1;   \
    pixels_out_mem[(i << 7) + 79] = pixels_mem_40_1;             \
    /* ---- ---- n 0/0 | ipe 40/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_41_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_41_0;        \
    pixels_41_0 = pixels_in_41.read();                           \
    pixels_out.write(pixels_41_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_41_0.range(RANGE_032_016));          \
    pixels_mem_41_0.range(RANGE_WRITER_032_000) = pixels_41_0;   \
    pixels_out_mem[(i << 7) + 80] = pixels_mem_41_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_41_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_41_1;        \
    pixels_41_1 = pixels_in_41.read();                           \
    pixels_out.write(pixels_41_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_41_1.range(RANGE_032_016));          \
    pixels_mem_41_1.range(RANGE_WRITER_032_000) = pixels_41_1;   \
    pixels_out_mem[(i << 7) + 81] = pixels_mem_41_1;             \
    /* ---- ---- n 0/0 | ipe 41/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_42_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_42_0;        \
    pixels_42_0 = pixels_in_42.read();                           \
    pixels_out.write(pixels_42_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_42_0.range(RANGE_032_016));          \
    pixels_mem_42_0.range(RANGE_WRITER_032_000) = pixels_42_0;   \
    pixels_out_mem[(i << 7) + 82] = pixels_mem_42_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_42_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_42_1;        \
    pixels_42_1 = pixels_in_42.read();                           \
    pixels_out.write(pixels_42_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_42_1.range(RANGE_032_016));          \
    pixels_mem_42_1.range(RANGE_WRITER_032_000) = pixels_42_1;   \
    pixels_out_mem[(i << 7) + 83] = pixels_mem_42_1;             \
    /* ---- ---- n 0/0 | ipe 42/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_43_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_43_0;        \
    pixels_43_0 = pixels_in_43.read();                           \
    pixels_out.write(pixels_43_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_43_0.range(RANGE_032_016));          \
    pixels_mem_43_0.range(RANGE_WRITER_032_000) = pixels_43_0;   \
    pixels_out_mem[(i << 7) + 84] = pixels_mem_43_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_43_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_43_1;        \
    pixels_43_1 = pixels_in_43.read();                           \
    pixels_out.write(pixels_43_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_43_1.range(RANGE_032_016));          \
    pixels_mem_43_1.range(RANGE_WRITER_032_000) = pixels_43_1;   \
    pixels_out_mem[(i << 7) + 85] = pixels_mem_43_1;             \
    /* ---- ---- n 0/0 | ipe 43/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_44_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_44_0;        \
    pixels_44_0 = pixels_in_44.read();                           \
    pixels_out.write(pixels_44_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_44_0.range(RANGE_032_016));          \
    pixels_mem_44_0.range(RANGE_WRITER_032_000) = pixels_44_0;   \
    pixels_out_mem[(i << 7) + 86] = pixels_mem_44_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_44_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_44_1;        \
    pixels_44_1 = pixels_in_44.read();                           \
    pixels_out.write(pixels_44_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_44_1.range(RANGE_032_016));          \
    pixels_mem_44_1.range(RANGE_WRITER_032_000) = pixels_44_1;   \
    pixels_out_mem[(i << 7) + 87] = pixels_mem_44_1;             \
    /* ---- ---- n 0/0 | ipe 44/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_45_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_45_0;        \
    pixels_45_0 = pixels_in_45.read();                           \
    pixels_out.write(pixels_45_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_45_0.range(RANGE_032_016));          \
    pixels_mem_45_0.range(RANGE_WRITER_032_000) = pixels_45_0;   \
    pixels_out_mem[(i << 7) + 88] = pixels_mem_45_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_45_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_45_1;        \
    pixels_45_1 = pixels_in_45.read();                           \
    pixels_out.write(pixels_45_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_45_1.range(RANGE_032_016));          \
    pixels_mem_45_1.range(RANGE_WRITER_032_000) = pixels_45_1;   \
    pixels_out_mem[(i << 7) + 89] = pixels_mem_45_1;             \
    /* ---- ---- n 0/0 | ipe 45/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_46_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_46_0;        \
    pixels_46_0 = pixels_in_46.read();                           \
    pixels_out.write(pixels_46_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_46_0.range(RANGE_032_016));          \
    pixels_mem_46_0.range(RANGE_WRITER_032_000) = pixels_46_0;   \
    pixels_out_mem[(i << 7) + 90] = pixels_mem_46_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_46_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_46_1;        \
    pixels_46_1 = pixels_in_46.read();                           \
    pixels_out.write(pixels_46_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_46_1.range(RANGE_032_016));          \
    pixels_mem_46_1.range(RANGE_WRITER_032_000) = pixels_46_1;   \
    pixels_out_mem[(i << 7) + 91] = pixels_mem_46_1;             \
    /* ---- ---- n 0/0 | ipe 46/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_47_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_47_0;        \
    pixels_47_0 = pixels_in_47.read();                           \
    pixels_out.write(pixels_47_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_47_0.range(RANGE_032_016));          \
    pixels_mem_47_0.range(RANGE_WRITER_032_000) = pixels_47_0;   \
    pixels_out_mem[(i << 7) + 92] = pixels_mem_47_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_47_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_47_1;        \
    pixels_47_1 = pixels_in_47.read();                           \
    pixels_out.write(pixels_47_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_47_1.range(RANGE_032_016));          \
    pixels_mem_47_1.range(RANGE_WRITER_032_000) = pixels_47_1;   \
    pixels_out_mem[(i << 7) + 93] = pixels_mem_47_1;             \
    /* ---- ---- n 0/0 | ipe 47/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_48_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_48_0;        \
    pixels_48_0 = pixels_in_48.read();                           \
    pixels_out.write(pixels_48_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_48_0.range(RANGE_032_016));          \
    pixels_mem_48_0.range(RANGE_WRITER_032_000) = pixels_48_0;   \
    pixels_out_mem[(i << 7) + 94] = pixels_mem_48_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_48_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_48_1;        \
    pixels_48_1 = pixels_in_48.read();                           \
    pixels_out.write(pixels_48_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_48_1.range(RANGE_032_016));          \
    pixels_mem_48_1.range(RANGE_WRITER_032_000) = pixels_48_1;   \
    pixels_out_mem[(i << 7) + 95] = pixels_mem_48_1;             \
    /* ---- ---- n 0/0 | ipe 48/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_49_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_49_0;        \
    pixels_49_0 = pixels_in_49.read();                           \
    pixels_out.write(pixels_49_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_49_0.range(RANGE_032_016));          \
    pixels_mem_49_0.range(RANGE_WRITER_032_000) = pixels_49_0;   \
    pixels_out_mem[(i << 7) + 96] = pixels_mem_49_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_49_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_49_1;        \
    pixels_49_1 = pixels_in_49.read();                           \
    pixels_out.write(pixels_49_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_49_1.range(RANGE_032_016));          \
    pixels_mem_49_1.range(RANGE_WRITER_032_000) = pixels_49_1;   \
    pixels_out_mem[(i << 7) + 97] = pixels_mem_49_1;             \
    /* ---- ---- n 0/0 | ipe 49/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_50_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_50_0;        \
    pixels_50_0 = pixels_in_50.read();                           \
    pixels_out.write(pixels_50_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_50_0.range(RANGE_032_016));          \
    pixels_mem_50_0.range(RANGE_WRITER_032_000) = pixels_50_0;   \
    pixels_out_mem[(i << 7) + 98] = pixels_mem_50_0;             \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_50_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_50_1;        \
    pixels_50_1 = pixels_in_50.read();                           \
    pixels_out.write(pixels_50_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_50_1.range(RANGE_032_016));          \
    pixels_mem_50_1.range(RANGE_WRITER_032_000) = pixels_50_1;   \
    pixels_out_mem[(i << 7) + 99] = pixels_mem_50_1;             \
    /* ---- ---- n 0/0 | ipe 50/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_51_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_51_0;        \
    pixels_51_0 = pixels_in_51.read();                           \
    pixels_out.write(pixels_51_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_51_0.range(RANGE_032_016));          \
    pixels_mem_51_0.range(RANGE_WRITER_032_000) = pixels_51_0;   \
    pixels_out_mem[(i << 7) + 100] = pixels_mem_51_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_51_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_51_1;        \
    pixels_51_1 = pixels_in_51.read();                           \
    pixels_out.write(pixels_51_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_51_1.range(RANGE_032_016));          \
    pixels_mem_51_1.range(RANGE_WRITER_032_000) = pixels_51_1;   \
    pixels_out_mem[(i << 7) + 101] = pixels_mem_51_1;            \
    /* ---- ---- n 0/0 | ipe 51/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_52_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_52_0;        \
    pixels_52_0 = pixels_in_52.read();                           \
    pixels_out.write(pixels_52_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_52_0.range(RANGE_032_016));          \
    pixels_mem_52_0.range(RANGE_WRITER_032_000) = pixels_52_0;   \
    pixels_out_mem[(i << 7) + 102] = pixels_mem_52_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_52_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_52_1;        \
    pixels_52_1 = pixels_in_52.read();                           \
    pixels_out.write(pixels_52_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_52_1.range(RANGE_032_016));          \
    pixels_mem_52_1.range(RANGE_WRITER_032_000) = pixels_52_1;   \
    pixels_out_mem[(i << 7) + 103] = pixels_mem_52_1;            \
    /* ---- ---- n 0/0 | ipe 52/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_53_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_53_0;        \
    pixels_53_0 = pixels_in_53.read();                           \
    pixels_out.write(pixels_53_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_53_0.range(RANGE_032_016));          \
    pixels_mem_53_0.range(RANGE_WRITER_032_000) = pixels_53_0;   \
    pixels_out_mem[(i << 7) + 104] = pixels_mem_53_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_53_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_53_1;        \
    pixels_53_1 = pixels_in_53.read();                           \
    pixels_out.write(pixels_53_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_53_1.range(RANGE_032_016));          \
    pixels_mem_53_1.range(RANGE_WRITER_032_000) = pixels_53_1;   \
    pixels_out_mem[(i << 7) + 105] = pixels_mem_53_1;            \
    /* ---- ---- n 0/0 | ipe 53/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_54_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_54_0;        \
    pixels_54_0 = pixels_in_54.read();                           \
    pixels_out.write(pixels_54_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_54_0.range(RANGE_032_016));          \
    pixels_mem_54_0.range(RANGE_WRITER_032_000) = pixels_54_0;   \
    pixels_out_mem[(i << 7) + 106] = pixels_mem_54_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_54_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_54_1;        \
    pixels_54_1 = pixels_in_54.read();                           \
    pixels_out.write(pixels_54_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_54_1.range(RANGE_032_016));          \
    pixels_mem_54_1.range(RANGE_WRITER_032_000) = pixels_54_1;   \
    pixels_out_mem[(i << 7) + 107] = pixels_mem_54_1;            \
    /* ---- ---- n 0/0 | ipe 54/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_55_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_55_0;        \
    pixels_55_0 = pixels_in_55.read();                           \
    pixels_out.write(pixels_55_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_55_0.range(RANGE_032_016));          \
    pixels_mem_55_0.range(RANGE_WRITER_032_000) = pixels_55_0;   \
    pixels_out_mem[(i << 7) + 108] = pixels_mem_55_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_55_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_55_1;        \
    pixels_55_1 = pixels_in_55.read();                           \
    pixels_out.write(pixels_55_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_55_1.range(RANGE_032_016));          \
    pixels_mem_55_1.range(RANGE_WRITER_032_000) = pixels_55_1;   \
    pixels_out_mem[(i << 7) + 109] = pixels_mem_55_1;            \
    /* ---- ---- n 0/0 | ipe 55/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_56_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_56_0;        \
    pixels_56_0 = pixels_in_56.read();                           \
    pixels_out.write(pixels_56_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_56_0.range(RANGE_032_016));          \
    pixels_mem_56_0.range(RANGE_WRITER_032_000) = pixels_56_0;   \
    pixels_out_mem[(i << 7) + 110] = pixels_mem_56_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_56_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_56_1;        \
    pixels_56_1 = pixels_in_56.read();                           \
    pixels_out.write(pixels_56_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_56_1.range(RANGE_032_016));          \
    pixels_mem_56_1.range(RANGE_WRITER_032_000) = pixels_56_1;   \
    pixels_out_mem[(i << 7) + 111] = pixels_mem_56_1;            \
    /* ---- ---- n 0/0 | ipe 56/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_57_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_57_0;        \
    pixels_57_0 = pixels_in_57.read();                           \
    pixels_out.write(pixels_57_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_57_0.range(RANGE_032_016));          \
    pixels_mem_57_0.range(RANGE_WRITER_032_000) = pixels_57_0;   \
    pixels_out_mem[(i << 7) + 112] = pixels_mem_57_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_57_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_57_1;        \
    pixels_57_1 = pixels_in_57.read();                           \
    pixels_out.write(pixels_57_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_57_1.range(RANGE_032_016));          \
    pixels_mem_57_1.range(RANGE_WRITER_032_000) = pixels_57_1;   \
    pixels_out_mem[(i << 7) + 113] = pixels_mem_57_1;            \
    /* ---- ---- n 0/0 | ipe 57/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_58_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_58_0;        \
    pixels_58_0 = pixels_in_58.read();                           \
    pixels_out.write(pixels_58_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_58_0.range(RANGE_032_016));          \
    pixels_mem_58_0.range(RANGE_WRITER_032_000) = pixels_58_0;   \
    pixels_out_mem[(i << 7) + 114] = pixels_mem_58_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_58_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_58_1;        \
    pixels_58_1 = pixels_in_58.read();                           \
    pixels_out.write(pixels_58_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_58_1.range(RANGE_032_016));          \
    pixels_mem_58_1.range(RANGE_WRITER_032_000) = pixels_58_1;   \
    pixels_out_mem[(i << 7) + 115] = pixels_mem_58_1;            \
    /* ---- ---- n 0/0 | ipe 58/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_59_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_59_0;        \
    pixels_59_0 = pixels_in_59.read();                           \
    pixels_out.write(pixels_59_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_59_0.range(RANGE_032_016));          \
    pixels_mem_59_0.range(RANGE_WRITER_032_000) = pixels_59_0;   \
    pixels_out_mem[(i << 7) + 116] = pixels_mem_59_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_59_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_59_1;        \
    pixels_59_1 = pixels_in_59.read();                           \
    pixels_out.write(pixels_59_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_59_1.range(RANGE_032_016));          \
    pixels_mem_59_1.range(RANGE_WRITER_032_000) = pixels_59_1;   \
    pixels_out_mem[(i << 7) + 117] = pixels_mem_59_1;            \
    /* ---- ---- n 0/0 | ipe 59/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_60_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_60_0;        \
    pixels_60_0 = pixels_in_60.read();                           \
    pixels_out.write(pixels_60_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_60_0.range(RANGE_032_016));          \
    pixels_mem_60_0.range(RANGE_WRITER_032_000) = pixels_60_0;   \
    pixels_out_mem[(i << 7) + 118] = pixels_mem_60_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_60_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_60_1;        \
    pixels_60_1 = pixels_in_60.read();                           \
    pixels_out.write(pixels_60_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_60_1.range(RANGE_032_016));          \
    pixels_mem_60_1.range(RANGE_WRITER_032_000) = pixels_60_1;   \
    pixels_out_mem[(i << 7) + 119] = pixels_mem_60_1;            \
    /* ---- ---- n 0/0 | ipe 60/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_61_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_61_0;        \
    pixels_61_0 = pixels_in_61.read();                           \
    pixels_out.write(pixels_61_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_61_0.range(RANGE_032_016));          \
    pixels_mem_61_0.range(RANGE_WRITER_032_000) = pixels_61_0;   \
    pixels_out_mem[(i << 7) + 120] = pixels_mem_61_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_61_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_61_1;        \
    pixels_61_1 = pixels_in_61.read();                           \
    pixels_out.write(pixels_61_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_61_1.range(RANGE_032_016));          \
    pixels_mem_61_1.range(RANGE_WRITER_032_000) = pixels_61_1;   \
    pixels_out_mem[(i << 7) + 121] = pixels_mem_61_1;            \
    /* ---- ---- n 0/0 | ipe 61/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_62_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_62_0;        \
    pixels_62_0 = pixels_in_62.read();                           \
    pixels_out.write(pixels_62_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_62_0.range(RANGE_032_016));          \
    pixels_mem_62_0.range(RANGE_WRITER_032_000) = pixels_62_0;   \
    pixels_out_mem[(i << 7) + 122] = pixels_mem_62_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_62_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_62_1;        \
    pixels_62_1 = pixels_in_62.read();                           \
    pixels_out.write(pixels_62_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_62_1.range(RANGE_032_016));          \
    pixels_mem_62_1.range(RANGE_WRITER_032_000) = pixels_62_1;   \
    pixels_out_mem[(i << 7) + 123] = pixels_mem_62_1;            \
    /* ---- ---- n 0/0 | ipe 62/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_63_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_63_0;        \
    pixels_63_0 = pixels_in_63.read();                           \
    pixels_out.write(pixels_63_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_63_0.range(RANGE_032_016));          \
    pixels_mem_63_0.range(RANGE_WRITER_032_000) = pixels_63_0;   \
    pixels_out_mem[(i << 7) + 124] = pixels_mem_63_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_63_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_63_1;        \
    pixels_63_1 = pixels_in_63.read();                           \
    pixels_out.write(pixels_63_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_63_1.range(RANGE_032_016));          \
    pixels_mem_63_1.range(RANGE_WRITER_032_000) = pixels_63_1;   \
    pixels_out_mem[(i << 7) + 125] = pixels_mem_63_1;            \
    /* ---- ---- n 0/0 | ipe 63/63 (saturated=True) ---- ---- */ \
    /* stride index 0/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_64_0;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_64_0;        \
    pixels_64_0 = pixels_in_64.read();                           \
    pixels_out.write(pixels_64_0.range(RANGE_016_000));          \
    pixels_out.write(pixels_64_0.range(RANGE_032_016));          \
    pixels_mem_64_0.range(RANGE_WRITER_032_000) = pixels_64_0;   \
    pixels_out_mem[(i << 7) + 126] = pixels_mem_64_0;            \
    /* stride index 1/1 */                                       \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_64_1;        \
    ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_64_1;        \
    pixels_64_1 = pixels_in_64.read();                           \
    pixels_out.write(pixels_64_1.range(RANGE_016_000));          \
    pixels_out.write(pixels_64_1.range(RANGE_032_016));          \
    pixels_mem_64_1.range(RANGE_WRITER_032_000) = pixels_64_1;   \
    pixels_out_mem[(i << 7) + 127] = pixels_mem_64_1;
