#pragma once

// This file is generated by data_movers/movers_generator.py

#define RANGE_032_000 255, 0

#define SETUP_INTERPOLATOR_SIGNATURE \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_1, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_2, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_3, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_4, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_5, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_6, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_7, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_8, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_9, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_10, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_11, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_12, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_13, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_14, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_15, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_16, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_17, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_18, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_19, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_20, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_21, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_22, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_23, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_24, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_25, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_26, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_27, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_28, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_29, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_30, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_31, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_32, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_33, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_34, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_35, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_36, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_37, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_38, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_39, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_40, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_41, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_42, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_43, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_44, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_45, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_46, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_47, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_48, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_49, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_50, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_51, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_52, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_53, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_54, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_55, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_56, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_57, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_58, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_59, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_60, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_61, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_62, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_63, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_64, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_65, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_66, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_67, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_68, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_69, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_70, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_71, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_72, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_73, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_74, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_75, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_76, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_77, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_78, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_79, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_80, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_81, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_82, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_83, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_84, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_85, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_86, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_87, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_88, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_89, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_90, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_91, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_92, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_93, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_94, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_95, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_96, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_97, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_98, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_99, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_100, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_101, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_102, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_103, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_104, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_105, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_106, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_107, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_108, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_109, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_110, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_111, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_112, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_113, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_114, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_115, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_116, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_117, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_118, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_119, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_120, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_121, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_122, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_123, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_124, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_125, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_126, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_127, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& out_128 \

#define SETUP_INTERPOLATOR_TESTBENCH_CALL(x) \
	x[0], \
	x[1], \
	x[2], \
	x[3], \
	x[4], \
	x[5], \
	x[6], \
	x[7], \
	x[8], \
	x[9], \
	x[10], \
	x[11], \
	x[12], \
	x[13], \
	x[14], \
	x[15], \
	x[16], \
	x[17], \
	x[18], \
	x[19], \
	x[20], \
	x[21], \
	x[22], \
	x[23], \
	x[24], \
	x[25], \
	x[26], \
	x[27], \
	x[28], \
	x[29], \
	x[30], \
	x[31], \
	x[32], \
	x[33], \
	x[34], \
	x[35], \
	x[36], \
	x[37], \
	x[38], \
	x[39], \
	x[40], \
	x[41], \
	x[42], \
	x[43], \
	x[44], \
	x[45], \
	x[46], \
	x[47], \
	x[48], \
	x[49], \
	x[50], \
	x[51], \
	x[52], \
	x[53], \
	x[54], \
	x[55], \
	x[56], \
	x[57], \
	x[58], \
	x[59], \
	x[60], \
	x[61], \
	x[62], \
	x[63], \
	x[64], \
	x[65], \
	x[66], \
	x[67], \
	x[68], \
	x[69], \
	x[70], \
	x[71], \
	x[72], \
	x[73], \
	x[74], \
	x[75], \
	x[76], \
	x[77], \
	x[78], \
	x[79], \
	x[80], \
	x[81], \
	x[82], \
	x[83], \
	x[84], \
	x[85], \
	x[86], \
	x[87], \
	x[88], \
	x[89], \
	x[90], \
	x[91], \
	x[92], \
	x[93], \
	x[94], \
	x[95], \
	x[96], \
	x[97], \
	x[98], \
	x[99], \
	x[100], \
	x[101], \
	x[102], \
	x[103], \
	x[104], \
	x[105], \
	x[106], \
	x[107], \
	x[108], \
	x[109], \
	x[110], \
	x[111], \
	x[112], \
	x[113], \
	x[114], \
	x[115], \
	x[116], \
	x[117], \
	x[118], \
	x[119], \
	x[120], \
	x[121], \
	x[122], \
	x[123], \
	x[124], \
	x[125], \
	x[126], \
	x[127] \

#define PRAGMA_SUB(x) _Pragma (#x) // source: https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/Using-Constants-with-Pragmas
#define PRAGMA_HLS(x) PRAGMA_SUB(x)
#define SETUP_INTERPOLATOR_PRAGMAS \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_1) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_2) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_3) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_4) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_5) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_6) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_7) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_8) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_9) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_10) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_11) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_12) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_13) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_14) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_15) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_16) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_17) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_18) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_19) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_20) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_21) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_22) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_23) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_24) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_25) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_26) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_27) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_28) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_29) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_30) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_31) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_32) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_33) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_34) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_35) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_36) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_37) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_38) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_39) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_40) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_41) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_42) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_43) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_44) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_45) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_46) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_47) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_48) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_49) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_50) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_51) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_52) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_53) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_54) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_55) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_56) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_57) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_58) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_59) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_60) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_61) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_62) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_63) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_64) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_65) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_66) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_67) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_68) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_69) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_70) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_71) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_72) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_73) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_74) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_75) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_76) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_77) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_78) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_79) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_80) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_81) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_82) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_83) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_84) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_85) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_86) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_87) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_88) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_89) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_90) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_91) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_92) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_93) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_94) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_95) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_96) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_97) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_98) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_99) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_100) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_101) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_102) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_103) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_104) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_105) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_106) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_107) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_108) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_109) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_110) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_111) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_112) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_113) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_114) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_115) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_116) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_117) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_118) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_119) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_120) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_121) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_122) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_123) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_124) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_125) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_126) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_127) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=out_128) \

#define SETUP_INTERPOLATOR_AIE_STARTER \
	data.range(7,0) = 0; \
	out_1.write(data); \
	out_1.write(data); \
	data.range(7,0) = 1; \
	out_2.write(data); \
	out_2.write(data); \
	data.range(7,0) = 2; \
	out_3.write(data); \
	out_3.write(data); \
	data.range(7,0) = 3; \
	out_4.write(data); \
	out_4.write(data); \
	data.range(7,0) = 4; \
	out_5.write(data); \
	out_5.write(data); \
	data.range(7,0) = 5; \
	out_6.write(data); \
	out_6.write(data); \
	data.range(7,0) = 6; \
	out_7.write(data); \
	out_7.write(data); \
	data.range(7,0) = 7; \
	out_8.write(data); \
	out_8.write(data); \
	data.range(7,0) = 8; \
	out_9.write(data); \
	out_9.write(data); \
	data.range(7,0) = 9; \
	out_10.write(data); \
	out_10.write(data); \
	data.range(7,0) = 10; \
	out_11.write(data); \
	out_11.write(data); \
	data.range(7,0) = 11; \
	out_12.write(data); \
	out_12.write(data); \
	data.range(7,0) = 12; \
	out_13.write(data); \
	out_13.write(data); \
	data.range(7,0) = 13; \
	out_14.write(data); \
	out_14.write(data); \
	data.range(7,0) = 14; \
	out_15.write(data); \
	out_15.write(data); \
	data.range(7,0) = 15; \
	out_16.write(data); \
	out_16.write(data); \
	data.range(7,0) = 16; \
	out_17.write(data); \
	out_17.write(data); \
	data.range(7,0) = 17; \
	out_18.write(data); \
	out_18.write(data); \
	data.range(7,0) = 18; \
	out_19.write(data); \
	out_19.write(data); \
	data.range(7,0) = 19; \
	out_20.write(data); \
	out_20.write(data); \
	data.range(7,0) = 20; \
	out_21.write(data); \
	out_21.write(data); \
	data.range(7,0) = 21; \
	out_22.write(data); \
	out_22.write(data); \
	data.range(7,0) = 22; \
	out_23.write(data); \
	out_23.write(data); \
	data.range(7,0) = 23; \
	out_24.write(data); \
	out_24.write(data); \
	data.range(7,0) = 24; \
	out_25.write(data); \
	out_25.write(data); \
	data.range(7,0) = 25; \
	out_26.write(data); \
	out_26.write(data); \
	data.range(7,0) = 26; \
	out_27.write(data); \
	out_27.write(data); \
	data.range(7,0) = 27; \
	out_28.write(data); \
	out_28.write(data); \
	data.range(7,0) = 28; \
	out_29.write(data); \
	out_29.write(data); \
	data.range(7,0) = 29; \
	out_30.write(data); \
	out_30.write(data); \
	data.range(7,0) = 30; \
	out_31.write(data); \
	out_31.write(data); \
	data.range(7,0) = 31; \
	out_32.write(data); \
	out_32.write(data); \
	data.range(7,0) = 32; \
	out_33.write(data); \
	out_33.write(data); \
	data.range(7,0) = 33; \
	out_34.write(data); \
	out_34.write(data); \
	data.range(7,0) = 34; \
	out_35.write(data); \
	out_35.write(data); \
	data.range(7,0) = 35; \
	out_36.write(data); \
	out_36.write(data); \
	data.range(7,0) = 36; \
	out_37.write(data); \
	out_37.write(data); \
	data.range(7,0) = 37; \
	out_38.write(data); \
	out_38.write(data); \
	data.range(7,0) = 38; \
	out_39.write(data); \
	out_39.write(data); \
	data.range(7,0) = 39; \
	out_40.write(data); \
	out_40.write(data); \
	data.range(7,0) = 40; \
	out_41.write(data); \
	out_41.write(data); \
	data.range(7,0) = 41; \
	out_42.write(data); \
	out_42.write(data); \
	data.range(7,0) = 42; \
	out_43.write(data); \
	out_43.write(data); \
	data.range(7,0) = 43; \
	out_44.write(data); \
	out_44.write(data); \
	data.range(7,0) = 44; \
	out_45.write(data); \
	out_45.write(data); \
	data.range(7,0) = 45; \
	out_46.write(data); \
	out_46.write(data); \
	data.range(7,0) = 46; \
	out_47.write(data); \
	out_47.write(data); \
	data.range(7,0) = 47; \
	out_48.write(data); \
	out_48.write(data); \
	data.range(7,0) = 48; \
	out_49.write(data); \
	out_49.write(data); \
	data.range(7,0) = 49; \
	out_50.write(data); \
	out_50.write(data); \
	data.range(7,0) = 50; \
	out_51.write(data); \
	out_51.write(data); \
	data.range(7,0) = 51; \
	out_52.write(data); \
	out_52.write(data); \
	data.range(7,0) = 52; \
	out_53.write(data); \
	out_53.write(data); \
	data.range(7,0) = 53; \
	out_54.write(data); \
	out_54.write(data); \
	data.range(7,0) = 54; \
	out_55.write(data); \
	out_55.write(data); \
	data.range(7,0) = 55; \
	out_56.write(data); \
	out_56.write(data); \
	data.range(7,0) = 56; \
	out_57.write(data); \
	out_57.write(data); \
	data.range(7,0) = 57; \
	out_58.write(data); \
	out_58.write(data); \
	data.range(7,0) = 58; \
	out_59.write(data); \
	out_59.write(data); \
	data.range(7,0) = 59; \
	out_60.write(data); \
	out_60.write(data); \
	data.range(7,0) = 60; \
	out_61.write(data); \
	out_61.write(data); \
	data.range(7,0) = 61; \
	out_62.write(data); \
	out_62.write(data); \
	data.range(7,0) = 62; \
	out_63.write(data); \
	out_63.write(data); \
	data.range(7,0) = 63; \
	out_64.write(data); \
	out_64.write(data); \
	data.range(7,0) = 64; \
	out_65.write(data); \
	out_65.write(data); \
	data.range(7,0) = 65; \
	out_66.write(data); \
	out_66.write(data); \
	data.range(7,0) = 66; \
	out_67.write(data); \
	out_67.write(data); \
	data.range(7,0) = 67; \
	out_68.write(data); \
	out_68.write(data); \
	data.range(7,0) = 68; \
	out_69.write(data); \
	out_69.write(data); \
	data.range(7,0) = 69; \
	out_70.write(data); \
	out_70.write(data); \
	data.range(7,0) = 70; \
	out_71.write(data); \
	out_71.write(data); \
	data.range(7,0) = 71; \
	out_72.write(data); \
	out_72.write(data); \
	data.range(7,0) = 72; \
	out_73.write(data); \
	out_73.write(data); \
	data.range(7,0) = 73; \
	out_74.write(data); \
	out_74.write(data); \
	data.range(7,0) = 74; \
	out_75.write(data); \
	out_75.write(data); \
	data.range(7,0) = 75; \
	out_76.write(data); \
	out_76.write(data); \
	data.range(7,0) = 76; \
	out_77.write(data); \
	out_77.write(data); \
	data.range(7,0) = 77; \
	out_78.write(data); \
	out_78.write(data); \
	data.range(7,0) = 78; \
	out_79.write(data); \
	out_79.write(data); \
	data.range(7,0) = 79; \
	out_80.write(data); \
	out_80.write(data); \
	data.range(7,0) = 80; \
	out_81.write(data); \
	out_81.write(data); \
	data.range(7,0) = 81; \
	out_82.write(data); \
	out_82.write(data); \
	data.range(7,0) = 82; \
	out_83.write(data); \
	out_83.write(data); \
	data.range(7,0) = 83; \
	out_84.write(data); \
	out_84.write(data); \
	data.range(7,0) = 84; \
	out_85.write(data); \
	out_85.write(data); \
	data.range(7,0) = 85; \
	out_86.write(data); \
	out_86.write(data); \
	data.range(7,0) = 86; \
	out_87.write(data); \
	out_87.write(data); \
	data.range(7,0) = 87; \
	out_88.write(data); \
	out_88.write(data); \
	data.range(7,0) = 88; \
	out_89.write(data); \
	out_89.write(data); \
	data.range(7,0) = 89; \
	out_90.write(data); \
	out_90.write(data); \
	data.range(7,0) = 90; \
	out_91.write(data); \
	out_91.write(data); \
	data.range(7,0) = 91; \
	out_92.write(data); \
	out_92.write(data); \
	data.range(7,0) = 92; \
	out_93.write(data); \
	out_93.write(data); \
	data.range(7,0) = 93; \
	out_94.write(data); \
	out_94.write(data); \
	data.range(7,0) = 94; \
	out_95.write(data); \
	out_95.write(data); \
	data.range(7,0) = 95; \
	out_96.write(data); \
	out_96.write(data); \
	data.range(7,0) = 96; \
	out_97.write(data); \
	out_97.write(data); \
	data.range(7,0) = 97; \
	out_98.write(data); \
	out_98.write(data); \
	data.range(7,0) = 98; \
	out_99.write(data); \
	out_99.write(data); \
	data.range(7,0) = 99; \
	out_100.write(data); \
	out_100.write(data); \
	data.range(7,0) = 100; \
	out_101.write(data); \
	out_101.write(data); \
	data.range(7,0) = 101; \
	out_102.write(data); \
	out_102.write(data); \
	data.range(7,0) = 102; \
	out_103.write(data); \
	out_103.write(data); \
	data.range(7,0) = 103; \
	out_104.write(data); \
	out_104.write(data); \
	data.range(7,0) = 104; \
	out_105.write(data); \
	out_105.write(data); \
	data.range(7,0) = 105; \
	out_106.write(data); \
	out_106.write(data); \
	data.range(7,0) = 106; \
	out_107.write(data); \
	out_107.write(data); \
	data.range(7,0) = 107; \
	out_108.write(data); \
	out_108.write(data); \
	data.range(7,0) = 108; \
	out_109.write(data); \
	out_109.write(data); \
	data.range(7,0) = 109; \
	out_110.write(data); \
	out_110.write(data); \
	data.range(7,0) = 110; \
	out_111.write(data); \
	out_111.write(data); \
	data.range(7,0) = 111; \
	out_112.write(data); \
	out_112.write(data); \
	data.range(7,0) = 112; \
	out_113.write(data); \
	out_113.write(data); \
	data.range(7,0) = 113; \
	out_114.write(data); \
	out_114.write(data); \
	data.range(7,0) = 114; \
	out_115.write(data); \
	out_115.write(data); \
	data.range(7,0) = 115; \
	out_116.write(data); \
	out_116.write(data); \
	data.range(7,0) = 116; \
	out_117.write(data); \
	out_117.write(data); \
	data.range(7,0) = 117; \
	out_118.write(data); \
	out_118.write(data); \
	data.range(7,0) = 118; \
	out_119.write(data); \
	out_119.write(data); \
	data.range(7,0) = 119; \
	out_120.write(data); \
	out_120.write(data); \
	data.range(7,0) = 120; \
	out_121.write(data); \
	out_121.write(data); \
	data.range(7,0) = 121; \
	out_122.write(data); \
	out_122.write(data); \
	data.range(7,0) = 122; \
	out_123.write(data); \
	out_123.write(data); \
	data.range(7,0) = 123; \
	out_124.write(data); \
	out_124.write(data); \
	data.range(7,0) = 124; \
	out_125.write(data); \
	out_125.write(data); \
	data.range(7,0) = 125; \
	out_126.write(data); \
	out_126.write(data); \
	data.range(7,0) = 126; \
	out_127.write(data); \
	out_127.write(data); \
	data.range(7,0) = 127; \
	out_128.write(data); \
	out_128.write(data); \

#define SETUP_INTERPOLATOR_BODY \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_1.write(A.range(RANGE_032_000)); \
	out_1.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_2.write(A.range(RANGE_032_000)); \
	out_2.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_3.write(A.range(RANGE_032_000)); \
	out_3.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_4.write(A.range(RANGE_032_000)); \
	out_4.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_5.write(A.range(RANGE_032_000)); \
	out_5.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_6.write(A.range(RANGE_032_000)); \
	out_6.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_7.write(A.range(RANGE_032_000)); \
	out_7.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_8.write(A.range(RANGE_032_000)); \
	out_8.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_9.write(A.range(RANGE_032_000)); \
	out_9.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_10.write(A.range(RANGE_032_000)); \
	out_10.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_11.write(A.range(RANGE_032_000)); \
	out_11.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_12.write(A.range(RANGE_032_000)); \
	out_12.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_13.write(A.range(RANGE_032_000)); \
	out_13.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_14.write(A.range(RANGE_032_000)); \
	out_14.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_15.write(A.range(RANGE_032_000)); \
	out_15.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_16.write(A.range(RANGE_032_000)); \
	out_16.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_17.write(A.range(RANGE_032_000)); \
	out_17.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_18.write(A.range(RANGE_032_000)); \
	out_18.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_19.write(A.range(RANGE_032_000)); \
	out_19.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_20.write(A.range(RANGE_032_000)); \
	out_20.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_21.write(A.range(RANGE_032_000)); \
	out_21.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_22.write(A.range(RANGE_032_000)); \
	out_22.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_23.write(A.range(RANGE_032_000)); \
	out_23.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_24.write(A.range(RANGE_032_000)); \
	out_24.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_25.write(A.range(RANGE_032_000)); \
	out_25.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_26.write(A.range(RANGE_032_000)); \
	out_26.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_27.write(A.range(RANGE_032_000)); \
	out_27.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_28.write(A.range(RANGE_032_000)); \
	out_28.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_29.write(A.range(RANGE_032_000)); \
	out_29.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_30.write(A.range(RANGE_032_000)); \
	out_30.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_31.write(A.range(RANGE_032_000)); \
	out_31.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_32.write(A.range(RANGE_032_000)); \
	out_32.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_33.write(A.range(RANGE_032_000)); \
	out_33.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_34.write(A.range(RANGE_032_000)); \
	out_34.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_35.write(A.range(RANGE_032_000)); \
	out_35.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_36.write(A.range(RANGE_032_000)); \
	out_36.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_37.write(A.range(RANGE_032_000)); \
	out_37.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_38.write(A.range(RANGE_032_000)); \
	out_38.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_39.write(A.range(RANGE_032_000)); \
	out_39.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_40.write(A.range(RANGE_032_000)); \
	out_40.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_41.write(A.range(RANGE_032_000)); \
	out_41.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_42.write(A.range(RANGE_032_000)); \
	out_42.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_43.write(A.range(RANGE_032_000)); \
	out_43.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_44.write(A.range(RANGE_032_000)); \
	out_44.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_45.write(A.range(RANGE_032_000)); \
	out_45.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_46.write(A.range(RANGE_032_000)); \
	out_46.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_47.write(A.range(RANGE_032_000)); \
	out_47.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_48.write(A.range(RANGE_032_000)); \
	out_48.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_49.write(A.range(RANGE_032_000)); \
	out_49.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_50.write(A.range(RANGE_032_000)); \
	out_50.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_51.write(A.range(RANGE_032_000)); \
	out_51.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_52.write(A.range(RANGE_032_000)); \
	out_52.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_53.write(A.range(RANGE_032_000)); \
	out_53.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_54.write(A.range(RANGE_032_000)); \
	out_54.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_55.write(A.range(RANGE_032_000)); \
	out_55.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_56.write(A.range(RANGE_032_000)); \
	out_56.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_57.write(A.range(RANGE_032_000)); \
	out_57.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_58.write(A.range(RANGE_032_000)); \
	out_58.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_59.write(A.range(RANGE_032_000)); \
	out_59.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_60.write(A.range(RANGE_032_000)); \
	out_60.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_61.write(A.range(RANGE_032_000)); \
	out_61.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_62.write(A.range(RANGE_032_000)); \
	out_62.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_63.write(A.range(RANGE_032_000)); \
	out_63.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_64.write(A.range(RANGE_032_000)); \
	out_64.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_65.write(A.range(RANGE_032_000)); \
	out_65.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_66.write(A.range(RANGE_032_000)); \
	out_66.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_67.write(A.range(RANGE_032_000)); \
	out_67.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_68.write(A.range(RANGE_032_000)); \
	out_68.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_69.write(A.range(RANGE_032_000)); \
	out_69.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_70.write(A.range(RANGE_032_000)); \
	out_70.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_71.write(A.range(RANGE_032_000)); \
	out_71.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_72.write(A.range(RANGE_032_000)); \
	out_72.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_73.write(A.range(RANGE_032_000)); \
	out_73.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_74.write(A.range(RANGE_032_000)); \
	out_74.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_75.write(A.range(RANGE_032_000)); \
	out_75.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_76.write(A.range(RANGE_032_000)); \
	out_76.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_77.write(A.range(RANGE_032_000)); \
	out_77.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_78.write(A.range(RANGE_032_000)); \
	out_78.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_79.write(A.range(RANGE_032_000)); \
	out_79.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_80.write(A.range(RANGE_032_000)); \
	out_80.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_81.write(A.range(RANGE_032_000)); \
	out_81.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_82.write(A.range(RANGE_032_000)); \
	out_82.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_83.write(A.range(RANGE_032_000)); \
	out_83.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_84.write(A.range(RANGE_032_000)); \
	out_84.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_85.write(A.range(RANGE_032_000)); \
	out_85.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_86.write(A.range(RANGE_032_000)); \
	out_86.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_87.write(A.range(RANGE_032_000)); \
	out_87.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_88.write(A.range(RANGE_032_000)); \
	out_88.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_89.write(A.range(RANGE_032_000)); \
	out_89.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_90.write(A.range(RANGE_032_000)); \
	out_90.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_91.write(A.range(RANGE_032_000)); \
	out_91.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_92.write(A.range(RANGE_032_000)); \
	out_92.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_93.write(A.range(RANGE_032_000)); \
	out_93.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_94.write(A.range(RANGE_032_000)); \
	out_94.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_95.write(A.range(RANGE_032_000)); \
	out_95.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_96.write(A.range(RANGE_032_000)); \
	out_96.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_97.write(A.range(RANGE_032_000)); \
	out_97.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_98.write(A.range(RANGE_032_000)); \
	out_98.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_99.write(A.range(RANGE_032_000)); \
	out_99.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_100.write(A.range(RANGE_032_000)); \
	out_100.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_101.write(A.range(RANGE_032_000)); \
	out_101.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_102.write(A.range(RANGE_032_000)); \
	out_102.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_103.write(A.range(RANGE_032_000)); \
	out_103.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_104.write(A.range(RANGE_032_000)); \
	out_104.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_105.write(A.range(RANGE_032_000)); \
	out_105.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_106.write(A.range(RANGE_032_000)); \
	out_106.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_107.write(A.range(RANGE_032_000)); \
	out_107.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_108.write(A.range(RANGE_032_000)); \
	out_108.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_109.write(A.range(RANGE_032_000)); \
	out_109.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_110.write(A.range(RANGE_032_000)); \
	out_110.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_111.write(A.range(RANGE_032_000)); \
	out_111.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_112.write(A.range(RANGE_032_000)); \
	out_112.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_113.write(A.range(RANGE_032_000)); \
	out_113.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_114.write(A.range(RANGE_032_000)); \
	out_114.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_115.write(A.range(RANGE_032_000)); \
	out_115.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_116.write(A.range(RANGE_032_000)); \
	out_116.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_117.write(A.range(RANGE_032_000)); \
	out_117.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_118.write(A.range(RANGE_032_000)); \
	out_118.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_119.write(A.range(RANGE_032_000)); \
	out_119.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_120.write(A.range(RANGE_032_000)); \
	out_120.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_121.write(A.range(RANGE_032_000)); \
	out_121.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_122.write(A.range(RANGE_032_000)); \
	out_122.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_123.write(A.range(RANGE_032_000)); \
	out_123.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_124.write(A.range(RANGE_032_000)); \
	out_124.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_125.write(A.range(RANGE_032_000)); \
	out_125.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_126.write(A.range(RANGE_032_000)); \
	out_126.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_127.write(A.range(RANGE_032_000)); \
	out_127.write(B.range(RANGE_032_000)); \
	A = Left_in.read(); \
	B = Right_in.read(); \
	out_128.write(A.range(RANGE_032_000)); \
	out_128.write(B.range(RANGE_032_000)); \

