#pragma once
// This file is generated by setup_mi_generator.py
// INT_PE = 128, n_streams and repetitions computed automatically

#define INT_PE_EXPO 7

#define RANGE_016_000 127, 0
#define RANGE_032_016 255, 128
#define RANGE_WRITER_032_000 255, 0

#define SETUP_MI_SIGNATURE \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_1, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_2, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_3, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_4, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_5, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_6, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_7, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_8, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_9, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_10, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_11, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_12, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_13, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_14, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_15, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_16, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_17, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_18, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_19, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_20, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_21, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_22, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_23, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_24, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_25, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_26, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_27, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_28, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_29, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_30, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_31, \
	hls::stream<ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN>>& pixels_in_32

#define SETUP_MI_TESTBENCH_CALL(x) \
	x[0], \
	x[1], \
	x[2], \
	x[3], \
	x[4], \
	x[5], \
	x[6], \
	x[7], \
	x[8], \
	x[9], \
	x[10], \
	x[11], \
	x[12], \
	x[13], \
	x[14], \
	x[15], \
	x[16], \
	x[17], \
	x[18], \
	x[19], \
	x[20], \
	x[21], \
	x[22], \
	x[23], \
	x[24], \
	x[25], \
	x[26], \
	x[27], \
	x[28], \
	x[29], \
	x[30], \
	x[31]

#define PRAGMA_SUB(x) _Pragma (#x)
#define PRAGMA_HLS(x) PRAGMA_SUB(x)

#define SETUP_MI_PRAGMAS \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_1) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_2) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_3) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_4) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_5) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_6) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_7) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_8) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_9) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_10) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_11) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_12) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_13) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_14) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_15) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_16) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_17) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_18) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_19) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_20) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_21) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_22) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_23) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_24) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_25) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_26) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_27) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_28) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_29) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_30) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_31) \
	PRAGMA_HLS(HLS interface axis depth=524288 port=pixels_in_32)

/* The last division is due to the unrolling factor computed at compile time */ \
#define SETUP_MI_VOLUME(n_row, n_col) \
const int unrolling_factor_expo = 0; \
const int VOLUME_withoutDepth = (((n_row * n_col) >> INT_PE_EXPO_SATURATED) >> 5) >> unrolling_factor_expo;

#define SETUP_MI_BODY \
	/* Auto-generated pixel reading and merging logic (AFFINE memory writes with shift) */ \
	/* n_streams = 32 */ \
	/* repetitions = 4 */ \
	/* index = (i << INT_PE_EXPO) + (stream_idx * repetitions + rep_idx) */ \
	/* ---- Stream 1/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_1; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_1_0; \
	pixels_1_0 = pixels_in_1.read(); \
	pixels_out.write(pixels_1_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_1_0.range(RANGE_032_016)); \
	pixels_mem_1.range(RANGE_WRITER_032_000) = pixels_1_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 0] = pixels_mem_1; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_1_1; \
	pixels_1_1 = pixels_in_1.read(); \
	pixels_out.write(pixels_1_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_1_1.range(RANGE_032_016)); \
	pixels_mem_1.range(RANGE_WRITER_032_000) = pixels_1_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 1] = pixels_mem_1; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_1_2; \
	pixels_1_2 = pixels_in_1.read(); \
	pixels_out.write(pixels_1_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_1_2.range(RANGE_032_016)); \
	pixels_mem_1.range(RANGE_WRITER_032_000) = pixels_1_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 2] = pixels_mem_1; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_1_3; \
	pixels_1_3 = pixels_in_1.read(); \
	pixels_out.write(pixels_1_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_1_3.range(RANGE_032_016)); \
	pixels_mem_1.range(RANGE_WRITER_032_000) = pixels_1_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 3] = pixels_mem_1; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 2/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_2; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_2_0; \
	pixels_2_0 = pixels_in_2.read(); \
	pixels_out.write(pixels_2_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_2_0.range(RANGE_032_016)); \
	pixels_mem_2.range(RANGE_WRITER_032_000) = pixels_2_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 4] = pixels_mem_2; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_2_1; \
	pixels_2_1 = pixels_in_2.read(); \
	pixels_out.write(pixels_2_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_2_1.range(RANGE_032_016)); \
	pixels_mem_2.range(RANGE_WRITER_032_000) = pixels_2_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 5] = pixels_mem_2; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_2_2; \
	pixels_2_2 = pixels_in_2.read(); \
	pixels_out.write(pixels_2_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_2_2.range(RANGE_032_016)); \
	pixels_mem_2.range(RANGE_WRITER_032_000) = pixels_2_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 6] = pixels_mem_2; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_2_3; \
	pixels_2_3 = pixels_in_2.read(); \
	pixels_out.write(pixels_2_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_2_3.range(RANGE_032_016)); \
	pixels_mem_2.range(RANGE_WRITER_032_000) = pixels_2_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 7] = pixels_mem_2; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 3/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_3; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_3_0; \
	pixels_3_0 = pixels_in_3.read(); \
	pixels_out.write(pixels_3_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_3_0.range(RANGE_032_016)); \
	pixels_mem_3.range(RANGE_WRITER_032_000) = pixels_3_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 8] = pixels_mem_3; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_3_1; \
	pixels_3_1 = pixels_in_3.read(); \
	pixels_out.write(pixels_3_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_3_1.range(RANGE_032_016)); \
	pixels_mem_3.range(RANGE_WRITER_032_000) = pixels_3_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 9] = pixels_mem_3; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_3_2; \
	pixels_3_2 = pixels_in_3.read(); \
	pixels_out.write(pixels_3_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_3_2.range(RANGE_032_016)); \
	pixels_mem_3.range(RANGE_WRITER_032_000) = pixels_3_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 10] = pixels_mem_3; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_3_3; \
	pixels_3_3 = pixels_in_3.read(); \
	pixels_out.write(pixels_3_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_3_3.range(RANGE_032_016)); \
	pixels_mem_3.range(RANGE_WRITER_032_000) = pixels_3_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 11] = pixels_mem_3; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 4/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_4; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_4_0; \
	pixels_4_0 = pixels_in_4.read(); \
	pixels_out.write(pixels_4_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_4_0.range(RANGE_032_016)); \
	pixels_mem_4.range(RANGE_WRITER_032_000) = pixels_4_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 12] = pixels_mem_4; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_4_1; \
	pixels_4_1 = pixels_in_4.read(); \
	pixels_out.write(pixels_4_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_4_1.range(RANGE_032_016)); \
	pixels_mem_4.range(RANGE_WRITER_032_000) = pixels_4_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 13] = pixels_mem_4; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_4_2; \
	pixels_4_2 = pixels_in_4.read(); \
	pixels_out.write(pixels_4_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_4_2.range(RANGE_032_016)); \
	pixels_mem_4.range(RANGE_WRITER_032_000) = pixels_4_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 14] = pixels_mem_4; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_4_3; \
	pixels_4_3 = pixels_in_4.read(); \
	pixels_out.write(pixels_4_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_4_3.range(RANGE_032_016)); \
	pixels_mem_4.range(RANGE_WRITER_032_000) = pixels_4_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 15] = pixels_mem_4; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 5/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_5; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_5_0; \
	pixels_5_0 = pixels_in_5.read(); \
	pixels_out.write(pixels_5_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_5_0.range(RANGE_032_016)); \
	pixels_mem_5.range(RANGE_WRITER_032_000) = pixels_5_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 16] = pixels_mem_5; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_5_1; \
	pixels_5_1 = pixels_in_5.read(); \
	pixels_out.write(pixels_5_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_5_1.range(RANGE_032_016)); \
	pixels_mem_5.range(RANGE_WRITER_032_000) = pixels_5_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 17] = pixels_mem_5; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_5_2; \
	pixels_5_2 = pixels_in_5.read(); \
	pixels_out.write(pixels_5_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_5_2.range(RANGE_032_016)); \
	pixels_mem_5.range(RANGE_WRITER_032_000) = pixels_5_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 18] = pixels_mem_5; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_5_3; \
	pixels_5_3 = pixels_in_5.read(); \
	pixels_out.write(pixels_5_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_5_3.range(RANGE_032_016)); \
	pixels_mem_5.range(RANGE_WRITER_032_000) = pixels_5_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 19] = pixels_mem_5; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 6/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_6; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_6_0; \
	pixels_6_0 = pixels_in_6.read(); \
	pixels_out.write(pixels_6_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_6_0.range(RANGE_032_016)); \
	pixels_mem_6.range(RANGE_WRITER_032_000) = pixels_6_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 20] = pixels_mem_6; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_6_1; \
	pixels_6_1 = pixels_in_6.read(); \
	pixels_out.write(pixels_6_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_6_1.range(RANGE_032_016)); \
	pixels_mem_6.range(RANGE_WRITER_032_000) = pixels_6_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 21] = pixels_mem_6; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_6_2; \
	pixels_6_2 = pixels_in_6.read(); \
	pixels_out.write(pixels_6_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_6_2.range(RANGE_032_016)); \
	pixels_mem_6.range(RANGE_WRITER_032_000) = pixels_6_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 22] = pixels_mem_6; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_6_3; \
	pixels_6_3 = pixels_in_6.read(); \
	pixels_out.write(pixels_6_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_6_3.range(RANGE_032_016)); \
	pixels_mem_6.range(RANGE_WRITER_032_000) = pixels_6_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 23] = pixels_mem_6; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 7/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_7; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_7_0; \
	pixels_7_0 = pixels_in_7.read(); \
	pixels_out.write(pixels_7_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_7_0.range(RANGE_032_016)); \
	pixels_mem_7.range(RANGE_WRITER_032_000) = pixels_7_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 24] = pixels_mem_7; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_7_1; \
	pixels_7_1 = pixels_in_7.read(); \
	pixels_out.write(pixels_7_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_7_1.range(RANGE_032_016)); \
	pixels_mem_7.range(RANGE_WRITER_032_000) = pixels_7_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 25] = pixels_mem_7; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_7_2; \
	pixels_7_2 = pixels_in_7.read(); \
	pixels_out.write(pixels_7_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_7_2.range(RANGE_032_016)); \
	pixels_mem_7.range(RANGE_WRITER_032_000) = pixels_7_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 26] = pixels_mem_7; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_7_3; \
	pixels_7_3 = pixels_in_7.read(); \
	pixels_out.write(pixels_7_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_7_3.range(RANGE_032_016)); \
	pixels_mem_7.range(RANGE_WRITER_032_000) = pixels_7_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 27] = pixels_mem_7; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 8/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_8; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_8_0; \
	pixels_8_0 = pixels_in_8.read(); \
	pixels_out.write(pixels_8_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_8_0.range(RANGE_032_016)); \
	pixels_mem_8.range(RANGE_WRITER_032_000) = pixels_8_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 28] = pixels_mem_8; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_8_1; \
	pixels_8_1 = pixels_in_8.read(); \
	pixels_out.write(pixels_8_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_8_1.range(RANGE_032_016)); \
	pixels_mem_8.range(RANGE_WRITER_032_000) = pixels_8_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 29] = pixels_mem_8; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_8_2; \
	pixels_8_2 = pixels_in_8.read(); \
	pixels_out.write(pixels_8_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_8_2.range(RANGE_032_016)); \
	pixels_mem_8.range(RANGE_WRITER_032_000) = pixels_8_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 30] = pixels_mem_8; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_8_3; \
	pixels_8_3 = pixels_in_8.read(); \
	pixels_out.write(pixels_8_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_8_3.range(RANGE_032_016)); \
	pixels_mem_8.range(RANGE_WRITER_032_000) = pixels_8_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 31] = pixels_mem_8; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 9/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_9; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_9_0; \
	pixels_9_0 = pixels_in_9.read(); \
	pixels_out.write(pixels_9_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_9_0.range(RANGE_032_016)); \
	pixels_mem_9.range(RANGE_WRITER_032_000) = pixels_9_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 32] = pixels_mem_9; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_9_1; \
	pixels_9_1 = pixels_in_9.read(); \
	pixels_out.write(pixels_9_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_9_1.range(RANGE_032_016)); \
	pixels_mem_9.range(RANGE_WRITER_032_000) = pixels_9_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 33] = pixels_mem_9; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_9_2; \
	pixels_9_2 = pixels_in_9.read(); \
	pixels_out.write(pixels_9_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_9_2.range(RANGE_032_016)); \
	pixels_mem_9.range(RANGE_WRITER_032_000) = pixels_9_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 34] = pixels_mem_9; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_9_3; \
	pixels_9_3 = pixels_in_9.read(); \
	pixels_out.write(pixels_9_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_9_3.range(RANGE_032_016)); \
	pixels_mem_9.range(RANGE_WRITER_032_000) = pixels_9_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 35] = pixels_mem_9; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 10/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_10; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_10_0; \
	pixels_10_0 = pixels_in_10.read(); \
	pixels_out.write(pixels_10_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_10_0.range(RANGE_032_016)); \
	pixels_mem_10.range(RANGE_WRITER_032_000) = pixels_10_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 36] = pixels_mem_10; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_10_1; \
	pixels_10_1 = pixels_in_10.read(); \
	pixels_out.write(pixels_10_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_10_1.range(RANGE_032_016)); \
	pixels_mem_10.range(RANGE_WRITER_032_000) = pixels_10_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 37] = pixels_mem_10; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_10_2; \
	pixels_10_2 = pixels_in_10.read(); \
	pixels_out.write(pixels_10_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_10_2.range(RANGE_032_016)); \
	pixels_mem_10.range(RANGE_WRITER_032_000) = pixels_10_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 38] = pixels_mem_10; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_10_3; \
	pixels_10_3 = pixels_in_10.read(); \
	pixels_out.write(pixels_10_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_10_3.range(RANGE_032_016)); \
	pixels_mem_10.range(RANGE_WRITER_032_000) = pixels_10_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 39] = pixels_mem_10; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 11/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_11; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_11_0; \
	pixels_11_0 = pixels_in_11.read(); \
	pixels_out.write(pixels_11_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_11_0.range(RANGE_032_016)); \
	pixels_mem_11.range(RANGE_WRITER_032_000) = pixels_11_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 40] = pixels_mem_11; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_11_1; \
	pixels_11_1 = pixels_in_11.read(); \
	pixels_out.write(pixels_11_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_11_1.range(RANGE_032_016)); \
	pixels_mem_11.range(RANGE_WRITER_032_000) = pixels_11_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 41] = pixels_mem_11; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_11_2; \
	pixels_11_2 = pixels_in_11.read(); \
	pixels_out.write(pixels_11_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_11_2.range(RANGE_032_016)); \
	pixels_mem_11.range(RANGE_WRITER_032_000) = pixels_11_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 42] = pixels_mem_11; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_11_3; \
	pixels_11_3 = pixels_in_11.read(); \
	pixels_out.write(pixels_11_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_11_3.range(RANGE_032_016)); \
	pixels_mem_11.range(RANGE_WRITER_032_000) = pixels_11_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 43] = pixels_mem_11; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 12/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_12; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_12_0; \
	pixels_12_0 = pixels_in_12.read(); \
	pixels_out.write(pixels_12_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_12_0.range(RANGE_032_016)); \
	pixels_mem_12.range(RANGE_WRITER_032_000) = pixels_12_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 44] = pixels_mem_12; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_12_1; \
	pixels_12_1 = pixels_in_12.read(); \
	pixels_out.write(pixels_12_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_12_1.range(RANGE_032_016)); \
	pixels_mem_12.range(RANGE_WRITER_032_000) = pixels_12_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 45] = pixels_mem_12; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_12_2; \
	pixels_12_2 = pixels_in_12.read(); \
	pixels_out.write(pixels_12_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_12_2.range(RANGE_032_016)); \
	pixels_mem_12.range(RANGE_WRITER_032_000) = pixels_12_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 46] = pixels_mem_12; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_12_3; \
	pixels_12_3 = pixels_in_12.read(); \
	pixels_out.write(pixels_12_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_12_3.range(RANGE_032_016)); \
	pixels_mem_12.range(RANGE_WRITER_032_000) = pixels_12_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 47] = pixels_mem_12; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 13/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_13; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_13_0; \
	pixels_13_0 = pixels_in_13.read(); \
	pixels_out.write(pixels_13_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_13_0.range(RANGE_032_016)); \
	pixels_mem_13.range(RANGE_WRITER_032_000) = pixels_13_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 48] = pixels_mem_13; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_13_1; \
	pixels_13_1 = pixels_in_13.read(); \
	pixels_out.write(pixels_13_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_13_1.range(RANGE_032_016)); \
	pixels_mem_13.range(RANGE_WRITER_032_000) = pixels_13_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 49] = pixels_mem_13; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_13_2; \
	pixels_13_2 = pixels_in_13.read(); \
	pixels_out.write(pixels_13_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_13_2.range(RANGE_032_016)); \
	pixels_mem_13.range(RANGE_WRITER_032_000) = pixels_13_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 50] = pixels_mem_13; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_13_3; \
	pixels_13_3 = pixels_in_13.read(); \
	pixels_out.write(pixels_13_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_13_3.range(RANGE_032_016)); \
	pixels_mem_13.range(RANGE_WRITER_032_000) = pixels_13_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 51] = pixels_mem_13; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 14/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_14; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_14_0; \
	pixels_14_0 = pixels_in_14.read(); \
	pixels_out.write(pixels_14_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_14_0.range(RANGE_032_016)); \
	pixels_mem_14.range(RANGE_WRITER_032_000) = pixels_14_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 52] = pixels_mem_14; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_14_1; \
	pixels_14_1 = pixels_in_14.read(); \
	pixels_out.write(pixels_14_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_14_1.range(RANGE_032_016)); \
	pixels_mem_14.range(RANGE_WRITER_032_000) = pixels_14_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 53] = pixels_mem_14; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_14_2; \
	pixels_14_2 = pixels_in_14.read(); \
	pixels_out.write(pixels_14_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_14_2.range(RANGE_032_016)); \
	pixels_mem_14.range(RANGE_WRITER_032_000) = pixels_14_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 54] = pixels_mem_14; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_14_3; \
	pixels_14_3 = pixels_in_14.read(); \
	pixels_out.write(pixels_14_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_14_3.range(RANGE_032_016)); \
	pixels_mem_14.range(RANGE_WRITER_032_000) = pixels_14_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 55] = pixels_mem_14; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 15/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_15; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_15_0; \
	pixels_15_0 = pixels_in_15.read(); \
	pixels_out.write(pixels_15_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_15_0.range(RANGE_032_016)); \
	pixels_mem_15.range(RANGE_WRITER_032_000) = pixels_15_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 56] = pixels_mem_15; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_15_1; \
	pixels_15_1 = pixels_in_15.read(); \
	pixels_out.write(pixels_15_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_15_1.range(RANGE_032_016)); \
	pixels_mem_15.range(RANGE_WRITER_032_000) = pixels_15_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 57] = pixels_mem_15; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_15_2; \
	pixels_15_2 = pixels_in_15.read(); \
	pixels_out.write(pixels_15_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_15_2.range(RANGE_032_016)); \
	pixels_mem_15.range(RANGE_WRITER_032_000) = pixels_15_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 58] = pixels_mem_15; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_15_3; \
	pixels_15_3 = pixels_in_15.read(); \
	pixels_out.write(pixels_15_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_15_3.range(RANGE_032_016)); \
	pixels_mem_15.range(RANGE_WRITER_032_000) = pixels_15_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 59] = pixels_mem_15; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 16/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_16; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_16_0; \
	pixels_16_0 = pixels_in_16.read(); \
	pixels_out.write(pixels_16_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_16_0.range(RANGE_032_016)); \
	pixels_mem_16.range(RANGE_WRITER_032_000) = pixels_16_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 60] = pixels_mem_16; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_16_1; \
	pixels_16_1 = pixels_in_16.read(); \
	pixels_out.write(pixels_16_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_16_1.range(RANGE_032_016)); \
	pixels_mem_16.range(RANGE_WRITER_032_000) = pixels_16_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 61] = pixels_mem_16; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_16_2; \
	pixels_16_2 = pixels_in_16.read(); \
	pixels_out.write(pixels_16_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_16_2.range(RANGE_032_016)); \
	pixels_mem_16.range(RANGE_WRITER_032_000) = pixels_16_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 62] = pixels_mem_16; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_16_3; \
	pixels_16_3 = pixels_in_16.read(); \
	pixels_out.write(pixels_16_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_16_3.range(RANGE_032_016)); \
	pixels_mem_16.range(RANGE_WRITER_032_000) = pixels_16_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 63] = pixels_mem_16; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 17/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_17; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_17_0; \
	pixels_17_0 = pixels_in_17.read(); \
	pixels_out.write(pixels_17_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_17_0.range(RANGE_032_016)); \
	pixels_mem_17.range(RANGE_WRITER_032_000) = pixels_17_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 64] = pixels_mem_17; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_17_1; \
	pixels_17_1 = pixels_in_17.read(); \
	pixels_out.write(pixels_17_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_17_1.range(RANGE_032_016)); \
	pixels_mem_17.range(RANGE_WRITER_032_000) = pixels_17_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 65] = pixels_mem_17; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_17_2; \
	pixels_17_2 = pixels_in_17.read(); \
	pixels_out.write(pixels_17_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_17_2.range(RANGE_032_016)); \
	pixels_mem_17.range(RANGE_WRITER_032_000) = pixels_17_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 66] = pixels_mem_17; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_17_3; \
	pixels_17_3 = pixels_in_17.read(); \
	pixels_out.write(pixels_17_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_17_3.range(RANGE_032_016)); \
	pixels_mem_17.range(RANGE_WRITER_032_000) = pixels_17_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 67] = pixels_mem_17; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 18/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_18; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_18_0; \
	pixels_18_0 = pixels_in_18.read(); \
	pixels_out.write(pixels_18_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_18_0.range(RANGE_032_016)); \
	pixels_mem_18.range(RANGE_WRITER_032_000) = pixels_18_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 68] = pixels_mem_18; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_18_1; \
	pixels_18_1 = pixels_in_18.read(); \
	pixels_out.write(pixels_18_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_18_1.range(RANGE_032_016)); \
	pixels_mem_18.range(RANGE_WRITER_032_000) = pixels_18_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 69] = pixels_mem_18; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_18_2; \
	pixels_18_2 = pixels_in_18.read(); \
	pixels_out.write(pixels_18_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_18_2.range(RANGE_032_016)); \
	pixels_mem_18.range(RANGE_WRITER_032_000) = pixels_18_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 70] = pixels_mem_18; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_18_3; \
	pixels_18_3 = pixels_in_18.read(); \
	pixels_out.write(pixels_18_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_18_3.range(RANGE_032_016)); \
	pixels_mem_18.range(RANGE_WRITER_032_000) = pixels_18_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 71] = pixels_mem_18; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 19/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_19; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_19_0; \
	pixels_19_0 = pixels_in_19.read(); \
	pixels_out.write(pixels_19_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_19_0.range(RANGE_032_016)); \
	pixels_mem_19.range(RANGE_WRITER_032_000) = pixels_19_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 72] = pixels_mem_19; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_19_1; \
	pixels_19_1 = pixels_in_19.read(); \
	pixels_out.write(pixels_19_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_19_1.range(RANGE_032_016)); \
	pixels_mem_19.range(RANGE_WRITER_032_000) = pixels_19_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 73] = pixels_mem_19; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_19_2; \
	pixels_19_2 = pixels_in_19.read(); \
	pixels_out.write(pixels_19_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_19_2.range(RANGE_032_016)); \
	pixels_mem_19.range(RANGE_WRITER_032_000) = pixels_19_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 74] = pixels_mem_19; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_19_3; \
	pixels_19_3 = pixels_in_19.read(); \
	pixels_out.write(pixels_19_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_19_3.range(RANGE_032_016)); \
	pixels_mem_19.range(RANGE_WRITER_032_000) = pixels_19_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 75] = pixels_mem_19; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 20/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_20; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_20_0; \
	pixels_20_0 = pixels_in_20.read(); \
	pixels_out.write(pixels_20_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_20_0.range(RANGE_032_016)); \
	pixels_mem_20.range(RANGE_WRITER_032_000) = pixels_20_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 76] = pixels_mem_20; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_20_1; \
	pixels_20_1 = pixels_in_20.read(); \
	pixels_out.write(pixels_20_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_20_1.range(RANGE_032_016)); \
	pixels_mem_20.range(RANGE_WRITER_032_000) = pixels_20_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 77] = pixels_mem_20; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_20_2; \
	pixels_20_2 = pixels_in_20.read(); \
	pixels_out.write(pixels_20_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_20_2.range(RANGE_032_016)); \
	pixels_mem_20.range(RANGE_WRITER_032_000) = pixels_20_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 78] = pixels_mem_20; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_20_3; \
	pixels_20_3 = pixels_in_20.read(); \
	pixels_out.write(pixels_20_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_20_3.range(RANGE_032_016)); \
	pixels_mem_20.range(RANGE_WRITER_032_000) = pixels_20_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 79] = pixels_mem_20; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 21/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_21; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_21_0; \
	pixels_21_0 = pixels_in_21.read(); \
	pixels_out.write(pixels_21_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_21_0.range(RANGE_032_016)); \
	pixels_mem_21.range(RANGE_WRITER_032_000) = pixels_21_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 80] = pixels_mem_21; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_21_1; \
	pixels_21_1 = pixels_in_21.read(); \
	pixels_out.write(pixels_21_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_21_1.range(RANGE_032_016)); \
	pixels_mem_21.range(RANGE_WRITER_032_000) = pixels_21_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 81] = pixels_mem_21; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_21_2; \
	pixels_21_2 = pixels_in_21.read(); \
	pixels_out.write(pixels_21_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_21_2.range(RANGE_032_016)); \
	pixels_mem_21.range(RANGE_WRITER_032_000) = pixels_21_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 82] = pixels_mem_21; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_21_3; \
	pixels_21_3 = pixels_in_21.read(); \
	pixels_out.write(pixels_21_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_21_3.range(RANGE_032_016)); \
	pixels_mem_21.range(RANGE_WRITER_032_000) = pixels_21_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 83] = pixels_mem_21; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 22/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_22; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_22_0; \
	pixels_22_0 = pixels_in_22.read(); \
	pixels_out.write(pixels_22_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_22_0.range(RANGE_032_016)); \
	pixels_mem_22.range(RANGE_WRITER_032_000) = pixels_22_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 84] = pixels_mem_22; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_22_1; \
	pixels_22_1 = pixels_in_22.read(); \
	pixels_out.write(pixels_22_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_22_1.range(RANGE_032_016)); \
	pixels_mem_22.range(RANGE_WRITER_032_000) = pixels_22_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 85] = pixels_mem_22; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_22_2; \
	pixels_22_2 = pixels_in_22.read(); \
	pixels_out.write(pixels_22_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_22_2.range(RANGE_032_016)); \
	pixels_mem_22.range(RANGE_WRITER_032_000) = pixels_22_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 86] = pixels_mem_22; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_22_3; \
	pixels_22_3 = pixels_in_22.read(); \
	pixels_out.write(pixels_22_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_22_3.range(RANGE_032_016)); \
	pixels_mem_22.range(RANGE_WRITER_032_000) = pixels_22_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 87] = pixels_mem_22; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 23/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_23; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_23_0; \
	pixels_23_0 = pixels_in_23.read(); \
	pixels_out.write(pixels_23_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_23_0.range(RANGE_032_016)); \
	pixels_mem_23.range(RANGE_WRITER_032_000) = pixels_23_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 88] = pixels_mem_23; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_23_1; \
	pixels_23_1 = pixels_in_23.read(); \
	pixels_out.write(pixels_23_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_23_1.range(RANGE_032_016)); \
	pixels_mem_23.range(RANGE_WRITER_032_000) = pixels_23_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 89] = pixels_mem_23; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_23_2; \
	pixels_23_2 = pixels_in_23.read(); \
	pixels_out.write(pixels_23_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_23_2.range(RANGE_032_016)); \
	pixels_mem_23.range(RANGE_WRITER_032_000) = pixels_23_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 90] = pixels_mem_23; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_23_3; \
	pixels_23_3 = pixels_in_23.read(); \
	pixels_out.write(pixels_23_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_23_3.range(RANGE_032_016)); \
	pixels_mem_23.range(RANGE_WRITER_032_000) = pixels_23_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 91] = pixels_mem_23; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 24/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_24; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_24_0; \
	pixels_24_0 = pixels_in_24.read(); \
	pixels_out.write(pixels_24_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_24_0.range(RANGE_032_016)); \
	pixels_mem_24.range(RANGE_WRITER_032_000) = pixels_24_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 92] = pixels_mem_24; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_24_1; \
	pixels_24_1 = pixels_in_24.read(); \
	pixels_out.write(pixels_24_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_24_1.range(RANGE_032_016)); \
	pixels_mem_24.range(RANGE_WRITER_032_000) = pixels_24_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 93] = pixels_mem_24; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_24_2; \
	pixels_24_2 = pixels_in_24.read(); \
	pixels_out.write(pixels_24_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_24_2.range(RANGE_032_016)); \
	pixels_mem_24.range(RANGE_WRITER_032_000) = pixels_24_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 94] = pixels_mem_24; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_24_3; \
	pixels_24_3 = pixels_in_24.read(); \
	pixels_out.write(pixels_24_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_24_3.range(RANGE_032_016)); \
	pixels_mem_24.range(RANGE_WRITER_032_000) = pixels_24_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 95] = pixels_mem_24; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 25/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_25; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_25_0; \
	pixels_25_0 = pixels_in_25.read(); \
	pixels_out.write(pixels_25_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_25_0.range(RANGE_032_016)); \
	pixels_mem_25.range(RANGE_WRITER_032_000) = pixels_25_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 96] = pixels_mem_25; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_25_1; \
	pixels_25_1 = pixels_in_25.read(); \
	pixels_out.write(pixels_25_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_25_1.range(RANGE_032_016)); \
	pixels_mem_25.range(RANGE_WRITER_032_000) = pixels_25_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 97] = pixels_mem_25; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_25_2; \
	pixels_25_2 = pixels_in_25.read(); \
	pixels_out.write(pixels_25_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_25_2.range(RANGE_032_016)); \
	pixels_mem_25.range(RANGE_WRITER_032_000) = pixels_25_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 98] = pixels_mem_25; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_25_3; \
	pixels_25_3 = pixels_in_25.read(); \
	pixels_out.write(pixels_25_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_25_3.range(RANGE_032_016)); \
	pixels_mem_25.range(RANGE_WRITER_032_000) = pixels_25_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 99] = pixels_mem_25; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 26/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_26; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_26_0; \
	pixels_26_0 = pixels_in_26.read(); \
	pixels_out.write(pixels_26_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_26_0.range(RANGE_032_016)); \
	pixels_mem_26.range(RANGE_WRITER_032_000) = pixels_26_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 100] = pixels_mem_26; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_26_1; \
	pixels_26_1 = pixels_in_26.read(); \
	pixels_out.write(pixels_26_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_26_1.range(RANGE_032_016)); \
	pixels_mem_26.range(RANGE_WRITER_032_000) = pixels_26_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 101] = pixels_mem_26; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_26_2; \
	pixels_26_2 = pixels_in_26.read(); \
	pixels_out.write(pixels_26_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_26_2.range(RANGE_032_016)); \
	pixels_mem_26.range(RANGE_WRITER_032_000) = pixels_26_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 102] = pixels_mem_26; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_26_3; \
	pixels_26_3 = pixels_in_26.read(); \
	pixels_out.write(pixels_26_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_26_3.range(RANGE_032_016)); \
	pixels_mem_26.range(RANGE_WRITER_032_000) = pixels_26_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 103] = pixels_mem_26; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 27/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_27; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_27_0; \
	pixels_27_0 = pixels_in_27.read(); \
	pixels_out.write(pixels_27_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_27_0.range(RANGE_032_016)); \
	pixels_mem_27.range(RANGE_WRITER_032_000) = pixels_27_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 104] = pixels_mem_27; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_27_1; \
	pixels_27_1 = pixels_in_27.read(); \
	pixels_out.write(pixels_27_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_27_1.range(RANGE_032_016)); \
	pixels_mem_27.range(RANGE_WRITER_032_000) = pixels_27_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 105] = pixels_mem_27; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_27_2; \
	pixels_27_2 = pixels_in_27.read(); \
	pixels_out.write(pixels_27_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_27_2.range(RANGE_032_016)); \
	pixels_mem_27.range(RANGE_WRITER_032_000) = pixels_27_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 106] = pixels_mem_27; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_27_3; \
	pixels_27_3 = pixels_in_27.read(); \
	pixels_out.write(pixels_27_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_27_3.range(RANGE_032_016)); \
	pixels_mem_27.range(RANGE_WRITER_032_000) = pixels_27_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 107] = pixels_mem_27; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 28/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_28; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_28_0; \
	pixels_28_0 = pixels_in_28.read(); \
	pixels_out.write(pixels_28_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_28_0.range(RANGE_032_016)); \
	pixels_mem_28.range(RANGE_WRITER_032_000) = pixels_28_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 108] = pixels_mem_28; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_28_1; \
	pixels_28_1 = pixels_in_28.read(); \
	pixels_out.write(pixels_28_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_28_1.range(RANGE_032_016)); \
	pixels_mem_28.range(RANGE_WRITER_032_000) = pixels_28_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 109] = pixels_mem_28; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_28_2; \
	pixels_28_2 = pixels_in_28.read(); \
	pixels_out.write(pixels_28_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_28_2.range(RANGE_032_016)); \
	pixels_mem_28.range(RANGE_WRITER_032_000) = pixels_28_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 110] = pixels_mem_28; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_28_3; \
	pixels_28_3 = pixels_in_28.read(); \
	pixels_out.write(pixels_28_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_28_3.range(RANGE_032_016)); \
	pixels_mem_28.range(RANGE_WRITER_032_000) = pixels_28_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 111] = pixels_mem_28; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 29/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_29; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_29_0; \
	pixels_29_0 = pixels_in_29.read(); \
	pixels_out.write(pixels_29_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_29_0.range(RANGE_032_016)); \
	pixels_mem_29.range(RANGE_WRITER_032_000) = pixels_29_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 112] = pixels_mem_29; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_29_1; \
	pixels_29_1 = pixels_in_29.read(); \
	pixels_out.write(pixels_29_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_29_1.range(RANGE_032_016)); \
	pixels_mem_29.range(RANGE_WRITER_032_000) = pixels_29_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 113] = pixels_mem_29; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_29_2; \
	pixels_29_2 = pixels_in_29.read(); \
	pixels_out.write(pixels_29_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_29_2.range(RANGE_032_016)); \
	pixels_mem_29.range(RANGE_WRITER_032_000) = pixels_29_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 114] = pixels_mem_29; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_29_3; \
	pixels_29_3 = pixels_in_29.read(); \
	pixels_out.write(pixels_29_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_29_3.range(RANGE_032_016)); \
	pixels_mem_29.range(RANGE_WRITER_032_000) = pixels_29_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 115] = pixels_mem_29; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 30/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_30; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_30_0; \
	pixels_30_0 = pixels_in_30.read(); \
	pixels_out.write(pixels_30_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_30_0.range(RANGE_032_016)); \
	pixels_mem_30.range(RANGE_WRITER_032_000) = pixels_30_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 116] = pixels_mem_30; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_30_1; \
	pixels_30_1 = pixels_in_30.read(); \
	pixels_out.write(pixels_30_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_30_1.range(RANGE_032_016)); \
	pixels_mem_30.range(RANGE_WRITER_032_000) = pixels_30_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 117] = pixels_mem_30; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_30_2; \
	pixels_30_2 = pixels_in_30.read(); \
	pixels_out.write(pixels_30_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_30_2.range(RANGE_032_016)); \
	pixels_mem_30.range(RANGE_WRITER_032_000) = pixels_30_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 118] = pixels_mem_30; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_30_3; \
	pixels_30_3 = pixels_in_30.read(); \
	pixels_out.write(pixels_30_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_30_3.range(RANGE_032_016)); \
	pixels_mem_30.range(RANGE_WRITER_032_000) = pixels_30_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 119] = pixels_mem_30; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 31/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_31; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_31_0; \
	pixels_31_0 = pixels_in_31.read(); \
	pixels_out.write(pixels_31_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_31_0.range(RANGE_032_016)); \
	pixels_mem_31.range(RANGE_WRITER_032_000) = pixels_31_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 120] = pixels_mem_31; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_31_1; \
	pixels_31_1 = pixels_in_31.read(); \
	pixels_out.write(pixels_31_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_31_1.range(RANGE_032_016)); \
	pixels_mem_31.range(RANGE_WRITER_032_000) = pixels_31_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 121] = pixels_mem_31; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_31_2; \
	pixels_31_2 = pixels_in_31.read(); \
	pixels_out.write(pixels_31_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_31_2.range(RANGE_032_016)); \
	pixels_mem_31.range(RANGE_WRITER_032_000) = pixels_31_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 122] = pixels_mem_31; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_31_3; \
	pixels_31_3 = pixels_in_31.read(); \
	pixels_out.write(pixels_31_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_31_3.range(RANGE_032_016)); \
	pixels_mem_31.range(RANGE_WRITER_032_000) = pixels_31_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 123] = pixels_mem_31; \
	/* ---------------------------------------------- */ \
	/* ---- Stream 32/32 ---- */ \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER> pixels_mem_32; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_32_0; \
	pixels_32_0 = pixels_in_32.read(); \
	pixels_out.write(pixels_32_0.range(RANGE_016_000)); \
	pixels_out.write(pixels_32_0.range(RANGE_032_016)); \
	pixels_mem_32.range(RANGE_WRITER_032_000) = pixels_32_0; \
	pixels_out_mem[(i << INT_PE_EXPO) + 124] = pixels_mem_32; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_32_1; \
	pixels_32_1 = pixels_in_32.read(); \
	pixels_out.write(pixels_32_1.range(RANGE_016_000)); \
	pixels_out.write(pixels_32_1.range(RANGE_032_016)); \
	pixels_mem_32.range(RANGE_WRITER_032_000) = pixels_32_1; \
	pixels_out_mem[(i << INT_PE_EXPO) + 125] = pixels_mem_32; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_32_2; \
	pixels_32_2 = pixels_in_32.read(); \
	pixels_out.write(pixels_32_2.range(RANGE_016_000)); \
	pixels_out.write(pixels_32_2.range(RANGE_032_016)); \
	pixels_mem_32.range(RANGE_WRITER_032_000) = pixels_32_2; \
	pixels_out_mem[(i << INT_PE_EXPO) + 126] = pixels_mem_32; \
	ap_uint<INPUT_DATA_BITWIDTH_FETCHER_MIN> pixels_32_3; \
	pixels_32_3 = pixels_in_32.read(); \
	pixels_out.write(pixels_32_3.range(RANGE_016_000)); \
	pixels_out.write(pixels_32_3.range(RANGE_032_016)); \
	pixels_mem_32.range(RANGE_WRITER_032_000) = pixels_32_3; \
	pixels_out_mem[(i << INT_PE_EXPO) + 127] = pixels_mem_32; \
	/* ---------------------------------------------- */

