# MIT License
# Copyright (c) 2025
# Giuseppe Sorrentino, Paolo Salvatore Galfano, Davide Conficconi, Eleonora D'Arnese

import argparse
import os


def main():
    parser = argparse.ArgumentParser(description='Generator for the hw-link configuration file')
    parser.add_argument("-in", "--input-template", nargs='?', help='cfg template', default='./xclbin_overlay.template.cfg', type=str)
    parser.add_argument("-out", "--output-cfg", nargs='?', help='generated cfg', default='./xclbin_overlay.cfg', type=str)
    parser.add_argument("-intpe", "--interpolator_pe_number", nargs='?', help='number of AIE interpolator PEs, default 1', default='1', type=int)
    parser.add_argument("-t", "--task", nargs='?', help='task to be built', choices=["TX","STEP"], default='STEP')

    args = parser.parse_args()

    interpolator_pe_number = args.interpolator_pe_number
    saturated_interpolator_pe_number = 128 if interpolator_pe_number > 128 else interpolator_pe_number
    task = args.task

    if interpolator_pe_number < 1:
        print("Error: interpolator_pe_number must be at least 1")
        exit(1)

    print(f"task: {task}")
    print(f"INT_PE = {interpolator_pe_number}")

    with open(args.input_template, "r") as config_file_in, open(args.output_cfg, "w") as config_file_out:
        lines = config_file_in.readlines()

        for idx, line in enumerate(lines):
            if "${" not in line:
                continue

            var_name = line.split("${")[1].split("}")[0]

            # =============================================================
            # 1️⃣  AIE → Writer/Setup_mi
            # =============================================================
            if var_name == "AIE_TO_WRITER":
                lines[idx] = ""

                # Calcolo numero stream
                if interpolator_pe_number <= 64:
                    num_streams = interpolator_pe_number // 2
                else:
                    num_streams = 32  # fisso per INT_PE > 64

                for i in range(1, num_streams + 1):
                    if task == "STEP":
                        lines[idx] += (
                            f"stream_connect = ai_engine_0.result_{i}:setup_mi_0.pixels_in_{i} "
                            f"# only for INT_PE>={i} (auto-generated by config_generator.py)\n"
                        )
                    elif task == "TX":
                        lines[idx] += (
                            f"stream_connect = ai_engine_0.result_{i}:writer_0.pixels_in_{i} "
                            f"# only for INT_PE>={i} (auto-generated by config_generator.py)\n"
                        )

            # =============================================================
            # 2️⃣  Scheduler → AIE
            # =============================================================
            elif var_name == "SINT_TO_AIE":
                lines[idx] = ""
                for i in range(0, saturated_interpolator_pe_number):
                    lines[idx] += (
                        f"stream_connect = scheduler_IPE_0.out_to_plio_{i}:ai_engine_0.p_ab_{i+1} "
                        f"# (auto-generated by config_generator.py)\n"
                    )

            else:
                print(f"Error: variable '{var_name}' not recognized")
                exit(1)

        # Final file write
        config_file_out.writelines(lines)

    print(f"[config_generator] Generated {args.output_cfg}")
    print(f" -> AIE_TO_WRITER streams: {num_streams}")
    print(f" -> SINT_TO_AIE streams: {saturated_interpolator_pe_number}")


if __name__ == "__main__":
    main()
